// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ai.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const decrementAIDailyQuotaUsed = `-- name: DecrementAIDailyQuotaUsed :one
UPDATE ai_daily_quota_usage
SET used = GREATEST(used - 1, 0),
    updated_at = now()
WHERE user_id = $1
  AND quota_date = $2
RETURNING used
`

type DecrementAIDailyQuotaUsedParams struct {
	UserID    string      `json:"userId"`
	QuotaDate pgtype.Date `json:"quotaDate"`
}

func (q *Queries) DecrementAIDailyQuotaUsed(ctx context.Context, arg DecrementAIDailyQuotaUsedParams) (int32, error) {
	row := q.db.QueryRow(ctx, decrementAIDailyQuotaUsed, arg.UserID, arg.QuotaDate)
	var used int32
	err := row.Scan(&used)
	return used, err
}

const deleteAIDailyQuotaUsageByUserID = `-- name: DeleteAIDailyQuotaUsageByUserID :exec
DELETE FROM ai_daily_quota_usage
WHERE user_id = $1
`

func (q *Queries) DeleteAIDailyQuotaUsageByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAIDailyQuotaUsageByUserID, userID)
	return err
}

const deleteOldDialogLogs = `-- name: DeleteOldDialogLogs :execrows
DELETE FROM ai_dialog_logs
WHERE id IN (
    SELECT id FROM ai_dialog_logs
    WHERE created_at < now() - interval '90 days'
    -- 按创建时间最旧优先删除，而非随机 UUID 顺序。
    ORDER BY created_at ASC
    LIMIT $1::bigint
)
`

func (q *Queries) DeleteOldDialogLogs(ctx context.Context, dollar_1 int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldDialogLogs, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAIDailyQuotaUsed = `-- name: GetAIDailyQuotaUsed :one
SELECT used FROM ai_daily_quota_usage
WHERE user_id = $1 AND quota_date = $2
`

type GetAIDailyQuotaUsedParams struct {
	UserID    string      `json:"userId"`
	QuotaDate pgtype.Date `json:"quotaDate"`
}

func (q *Queries) GetAIDailyQuotaUsed(ctx context.Context, arg GetAIDailyQuotaUsedParams) (int32, error) {
	row := q.db.QueryRow(ctx, getAIDailyQuotaUsed, arg.UserID, arg.QuotaDate)
	var used int32
	err := row.Scan(&used)
	return used, err
}

const incrementAIDailyQuotaUsed = `-- name: IncrementAIDailyQuotaUsed :one
WITH upsert AS (
    INSERT INTO ai_daily_quota_usage (user_id, quota_date, used, created_at, updated_at)
    VALUES ($1, $2, 1, now(), now())
    ON CONFLICT (user_id, quota_date)
    DO UPDATE SET
        used = ai_daily_quota_usage.used + 1,
        updated_at = now()
    WHERE ai_daily_quota_usage.used < $3
    RETURNING used
)
SELECT u.used, true AS incremented
FROM upsert u
UNION ALL
SELECT d.used, false AS incremented
FROM ai_daily_quota_usage d
WHERE d.user_id = $1 AND d.quota_date = $2
  AND NOT EXISTS (SELECT 1 FROM upsert)
`

type IncrementAIDailyQuotaUsedParams struct {
	UserID    string      `json:"userId"`
	QuotaDate pgtype.Date `json:"quotaDate"`
	Used      int32       `json:"used"`
}

type IncrementAIDailyQuotaUsedRow struct {
	Used        int32 `json:"used"`
	Incremented bool  `json:"incremented"`
}

func (q *Queries) IncrementAIDailyQuotaUsed(ctx context.Context, arg IncrementAIDailyQuotaUsedParams) (IncrementAIDailyQuotaUsedRow, error) {
	row := q.db.QueryRow(ctx, incrementAIDailyQuotaUsed, arg.UserID, arg.QuotaDate, arg.Used)
	var i IncrementAIDailyQuotaUsedRow
	err := row.Scan(&i.Used, &i.Incremented)
	return i, err
}

const insertAIDialogLog = `-- name: InsertAIDialogLog :exec
INSERT INTO ai_dialog_logs (id, user_id, role, content, created_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertAIDialogLogParams struct {
	ID        string             `json:"id"`
	UserID    string             `json:"userId"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) InsertAIDialogLog(ctx context.Context, arg InsertAIDialogLogParams) error {
	_, err := q.db.Exec(ctx, insertAIDialogLog,
		arg.ID,
		arg.UserID,
		arg.Role,
		arg.Content,
		arg.CreatedAt,
	)
	return err
}

const listAIBackgroundEntries = `-- name: ListAIBackgroundEntries :many
SELECT
    COALESCE(NULLIF(TRIM(u.nickname), ''), '家人')::text AS nickname,
    string_agg(
        to_char(sub.record_at AT TIME ZONE 'Asia/Shanghai', 'YYYYMMDD HH24"时"') ||
        CASE WHEN sub.detail_address <> '' THEN ' | ' || sub.detail_address ELSE '' END ||
        CASE WHEN sub.text <> '' THEN ' | ' || sub.text ELSE '' END,
        E'\n' ORDER BY sub.record_at DESC
    )::text AS content
FROM family_members fm
JOIN users u ON u.id = fm.user_id
JOIN LATERAL (
    SELECT
        COALESCE(de.record_time, de.created_at) AS record_at,
        COALESCE(NULLIF(TRIM(de.address), ''), NULLIF(TRIM(de.detail_address), ''), '')::text AS detail_address,
        COALESCE(NULLIF(TRIM(de.text), ''), '') AS text
    FROM diaries d
    JOIN diary_entries de ON de.diary_id = d.id
    WHERE d.user_id = fm.user_id
      AND de.created_at > now() - interval '90 days'
    ORDER BY de.created_at DESC
    LIMIT 500
) sub ON true
WHERE fm.family_id = $1
GROUP BY fm.user_id, u.nickname
ORDER BY MIN(sub.record_at) DESC
LIMIT $2
`

type ListAIBackgroundEntriesParams struct {
	FamilyID string `json:"familyId"`
	Limit    int32  `json:"limit"`
}

type ListAIBackgroundEntriesRow struct {
	Nickname string `json:"nickname"`
	Content  string `json:"content"`
}

func (q *Queries) ListAIBackgroundEntries(ctx context.Context, arg ListAIBackgroundEntriesParams) ([]ListAIBackgroundEntriesRow, error) {
	rows, err := q.db.Query(ctx, listAIBackgroundEntries, arg.FamilyID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAIBackgroundEntriesRow{}
	for rows.Next() {
		var i ListAIBackgroundEntriesRow
		if err := rows.Scan(&i.Nickname, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiaryEntriesByDateRange = `-- name: ListDiaryEntriesByDateRange :many
SELECT
    COALESCE(de.record_time, de.created_at) AS created_at,
    COALESCE(NULLIF(TRIM(de.text), ''), '')::text AS content,
    COALESCE(NULLIF(TRIM(de.address), ''), '')::text AS location
FROM diary_entries de
JOIN diaries d ON d.id = de.diary_id
WHERE d.user_id = $1
  AND d.record_date >= $2::date
  AND d.record_date <= $3::date
ORDER BY COALESCE(de.record_time, de.created_at) DESC
LIMIT $4
`

type ListDiaryEntriesByDateRangeParams struct {
	UserID  string      `json:"userId"`
	Column2 pgtype.Date `json:"column2"`
	Column3 pgtype.Date `json:"column3"`
	Limit   int32       `json:"limit"`
}

type ListDiaryEntriesByDateRangeRow struct {
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	Content   string             `json:"content"`
	Location  string             `json:"location"`
}

// 排序与展示列同源：record_time 被编辑后结果顺序仍与展示值一致。
func (q *Queries) ListDiaryEntriesByDateRange(ctx context.Context, arg ListDiaryEntriesByDateRangeParams) ([]ListDiaryEntriesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listDiaryEntriesByDateRange,
		arg.UserID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiaryEntriesByDateRangeRow{}
	for rows.Next() {
		var i ListDiaryEntriesByDateRangeRow
		if err := rows.Scan(&i.CreatedAt, &i.Content, &i.Location); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentDialogLogs = `-- name: ListRecentDialogLogs :many
SELECT id, user_id, role, content, created_at FROM ai_dialog_logs
WHERE user_id = $1
  AND created_at > now() - interval '7 days'
ORDER BY created_at DESC
LIMIT $2
`

type ListRecentDialogLogsParams struct {
	UserID string `json:"userId"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListRecentDialogLogs(ctx context.Context, arg ListRecentDialogLogsParams) ([]AiDialogLog, error) {
	rows, err := q.db.Query(ctx, listRecentDialogLogs, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AiDialogLog{}
	for rows.Next() {
		var i AiDialogLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.Content,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
