// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_key.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one
INSERT INTO api_keys (id, user_id, key_hash, api_key, created_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (user_id) DO NOTHING
RETURNING id, user_id, key_hash, api_key, created_at
`

type CreateAPIKeyParams struct {
	ID      string `json:"id"`
	UserID  string `json:"userId"`
	KeyHash string `json:"keyHash"`
	ApiKey  string `json:"apiKey"`
}

type CreateAPIKeyRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"userId"`
	KeyHash   string             `json:"keyHash"`
	ApiKey    string             `json:"apiKey"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

// expires_at 由列 DEFAULT 填充（恒 9999-12-31，000015），代码不再显式写入。
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.KeyHash,
		arg.ApiKey,
	)
	var i CreateAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKeyByUser = `-- name: DeleteAPIKeyByUser :exec
DELETE FROM api_keys WHERE user_id = $1
`

func (q *Queries) DeleteAPIKeyByUser(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAPIKeyByUser, userID)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, user_id, key_hash, api_key, created_at FROM api_keys WHERE key_hash = $1
`

type GetAPIKeyByHashRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"userId"`
	KeyHash   string             `json:"keyHash"`
	ApiKey    string             `json:"apiKey"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}

const getAPIKeyByUser = `-- name: GetAPIKeyByUser :one
SELECT id, user_id, key_hash, api_key, created_at FROM api_keys WHERE user_id = $1
`

type GetAPIKeyByUserRow struct {
	ID        string             `json:"id"`
	UserID    string             `json:"userId"`
	KeyHash   string             `json:"keyHash"`
	ApiKey    string             `json:"apiKey"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) GetAPIKeyByUser(ctx context.Context, userID string) (GetAPIKeyByUserRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByUser, userID)
	var i GetAPIKeyByUserRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.KeyHash,
		&i.ApiKey,
		&i.CreatedAt,
	)
	return i, err
}
