// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auto_record.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAutoRecordCandidates = `-- name: CountAutoRecordCandidates :one
SELECT count(*)::bigint
FROM users u
JOIN user_vips v ON v.user_id = u.id
WHERE u.auto_record_enabled = true
  AND v.expire_time > now()
  AND EXISTS (
      SELECT 1 FROM auto_record_trajectories t
      WHERE t.user_id = u.id AND t.geocode_attempts < $1
  )
`

// R-01：候选积压量（满批时才统计），超过阈值输出 auto_record_backlog_warn。
func (q *Queries) CountAutoRecordCandidates(ctx context.Context, maxGeocodeAttempts int32) (int64, error) {
	row := q.db.QueryRow(ctx, countAutoRecordCandidates, maxGeocodeAttempts)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteStaleTrajectories = `-- name: DeleteStaleTrajectories :execrows
DELETE FROM auto_record_trajectories
WHERE id IN (
    SELECT id FROM auto_record_trajectories
    WHERE created_at < now() - interval '7 days'
    ORDER BY id ASC
    LIMIT $1::bigint
)
`

func (q *Queries) DeleteStaleTrajectories(ctx context.Context, dollar_1 int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStaleTrajectories, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteTrajectories = `-- name: DeleteTrajectories :exec
DELETE FROM auto_record_trajectories WHERE id = ANY($1::text[])
`

func (q *Queries) DeleteTrajectories(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, deleteTrajectories, dollar_1)
	return err
}

const incrementTrajectoryGeocodeAttempts = `-- name: IncrementTrajectoryGeocodeAttempts :exec
UPDATE auto_record_trajectories
SET geocode_attempts = geocode_attempts + 1
WHERE id = ANY($1::text[])
`

func (q *Queries) IncrementTrajectoryGeocodeAttempts(ctx context.Context, dollar_1 []string) error {
	_, err := q.db.Exec(ctx, incrementTrajectoryGeocodeAttempts, dollar_1)
	return err
}

const insertTrajectories = `-- name: InsertTrajectories :exec
INSERT INTO auto_record_trajectories (id, user_id, lat, lon, recorded_at, geocode_attempts, created_at)
SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::text[])::numeric, unnest($4::text[])::numeric, unnest($5::timestamptz[]), 0, now()
ON CONFLICT DO NOTHING
`

type InsertTrajectoriesParams struct {
	Ids         []string             `json:"ids"`
	UserIds     []string             `json:"userIds"`
	Lats        []string             `json:"lats"`
	Lons        []string             `json:"lons"`
	RecordedAts []pgtype.Timestamptz `json:"recordedAts"`
}

// PPJ-C04：重复上报（同一 user+recorded_at+lat+lon）静默忽略，避免重试产生重复轨迹。
func (q *Queries) InsertTrajectories(ctx context.Context, arg InsertTrajectoriesParams) error {
	_, err := q.db.Exec(ctx, insertTrajectories,
		arg.Ids,
		arg.UserIds,
		arg.Lats,
		arg.Lons,
		arg.RecordedAts,
	)
	return err
}

const listAbnormalAlertCandidates = `-- name: ListAbnormalAlertCandidates :many
SELECT u.id, u.unionid, u.abnormal_subscribe_accepted
FROM users u
JOIN user_vips v ON v.user_id = u.id
LEFT JOIN LATERAL (
    SELECT MAX(t.recorded_at) AS last_recorded_at
    FROM auto_record_trajectories t
    WHERE t.user_id = u.id
) lt ON true
WHERE u.auto_record_enabled = true
  -- PPJ-C01：告警发送侧用严格 VIP（无宽限），候选侧也须严格，否则过期用户每轮入选又被跳过。
  AND v.expire_time > now()
  AND (
      u.abnormal_alert_sent_at IS NULL
      OR u.abnormal_alert_sent_at < now() - interval '1 hour'
  )
  AND (
      u.last_active_at IS NULL
      OR u.last_active_at < $1::timestamptz
  )
  AND COALESCE(lt.last_recorded_at, '1970-01-01'::timestamptz) < $1::timestamptz
  AND (
      u.abnormal_subscribe_accepted = true
      OR EXISTS (SELECT 1 FROM wx_mp_accounts mp WHERE mp.user_id = u.id AND mp.subscribed = true)
  )
LIMIT $2::bigint
`

type ListAbnormalAlertCandidatesParams struct {
	Column1 pgtype.Timestamptz `json:"column1"`
	Column2 int64              `json:"column2"`
}

type ListAbnormalAlertCandidatesRow struct {
	ID                        string      `json:"id"`
	Unionid                   pgtype.Text `json:"unionid"`
	AbnormalSubscribeAccepted bool        `json:"abnormalSubscribeAccepted"`
}

func (q *Queries) ListAbnormalAlertCandidates(ctx context.Context, arg ListAbnormalAlertCandidatesParams) ([]ListAbnormalAlertCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listAbnormalAlertCandidates, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAbnormalAlertCandidatesRow{}
	for rows.Next() {
		var i ListAbnormalAlertCandidatesRow
		if err := rows.Scan(&i.ID, &i.Unionid, &i.AbnormalSubscribeAccepted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAutoRecordCandidates = `-- name: ListAutoRecordCandidates :many
SELECT u.id AS user_id
FROM users u
JOIN user_vips v ON v.user_id = u.id
WHERE u.auto_record_enabled = true
  AND v.expire_time > now()
  AND u.id > $1
  AND EXISTS (
      SELECT 1 FROM auto_record_trajectories t
      WHERE t.user_id = u.id AND t.geocode_attempts < $2
  )
ORDER BY u.id ASC
LIMIT $3
`

type ListAutoRecordCandidatesParams struct {
	CursorID           string `json:"cursorId"`
	MaxGeocodeAttempts int32  `json:"maxGeocodeAttempts"`
	MaxUsers           int32  `json:"maxUsers"`
}

// R-01：公平轮转——按 user_id keyset 分页，替代「按积压量 ORDER BY cnt DESC」避免低频用户饥饿；
// 仅取仍有未达重试上限轨迹的用户（R-02）。
func (q *Queries) ListAutoRecordCandidates(ctx context.Context, arg ListAutoRecordCandidatesParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listAutoRecordCandidates, arg.CursorID, arg.MaxGeocodeAttempts, arg.MaxUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrajectoriesByUser = `-- name: ListTrajectoriesByUser :many
SELECT id, user_id, lat, lon, recorded_at, geocode_attempts, created_at FROM auto_record_trajectories
WHERE user_id = $1
  AND geocode_attempts < $2
ORDER BY recorded_at ASC
LIMIT $3
`

type ListTrajectoriesByUserParams struct {
	UserID             string `json:"userId"`
	MaxGeocodeAttempts int32  `json:"maxGeocodeAttempts"`
	MaxRows            int32  `json:"maxRows"`
}

// R-02：排除达到逆地理重试上限的终态轨迹，避免其每轮重复聚类/告警（保留至 7 天清理）。
func (q *Queries) ListTrajectoriesByUser(ctx context.Context, arg ListTrajectoriesByUserParams) ([]AutoRecordTrajectory, error) {
	rows, err := q.db.Query(ctx, listTrajectoriesByUser, arg.UserID, arg.MaxGeocodeAttempts, arg.MaxRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AutoRecordTrajectory{}
	for rows.Next() {
		var i AutoRecordTrajectory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Lat,
			&i.Lon,
			&i.RecordedAt,
			&i.GeocodeAttempts,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
