// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diary.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearFamilyDailyImageCoverByFileID = `-- name: ClearFamilyDailyImageCoverByFileID :exec
UPDATE family_daily_covers
SET cover_file_id = NULL,
    cover_type = 'default',
    updated_at = now()
WHERE family_id = $1
  AND record_date = $2
  AND cover_type = 'image'
  AND cover_file_id = $3
`

type ClearFamilyDailyImageCoverByFileIDParams struct {
	FamilyID    string      `json:"familyId"`
	RecordDate  pgtype.Date `json:"recordDate"`
	CoverFileID pgtype.Text `json:"coverFileId"`
}

func (q *Queries) ClearFamilyDailyImageCoverByFileID(ctx context.Context, arg ClearFamilyDailyImageCoverByFileIDParams) error {
	_, err := q.db.Exec(ctx, clearFamilyDailyImageCoverByFileID, arg.FamilyID, arg.RecordDate, arg.CoverFileID)
	return err
}

const clearFamilyDailyImageCoverByFileIDs = `-- name: ClearFamilyDailyImageCoverByFileIDs :exec
UPDATE family_daily_covers
SET cover_file_id = NULL,
    cover_type = 'default',
    updated_at = now()
WHERE family_id = $1
  AND record_date = $2
  AND cover_type = 'image'
  AND cover_file_id = ANY($3::text[])
`

type ClearFamilyDailyImageCoverByFileIDsParams struct {
	FamilyID   string      `json:"familyId"`
	RecordDate pgtype.Date `json:"recordDate"`
	Column3    []string    `json:"column3"`
}

func (q *Queries) ClearFamilyDailyImageCoverByFileIDs(ctx context.Context, arg ClearFamilyDailyImageCoverByFileIDsParams) error {
	_, err := q.db.Exec(ctx, clearFamilyDailyImageCoverByFileIDs, arg.FamilyID, arg.RecordDate, arg.Column3)
	return err
}

const clearFamilyDailyManualCover = `-- name: ClearFamilyDailyManualCover :exec
UPDATE family_daily_covers
SET manual_cover_file_id = NULL,
    cover_file_id = CASE WHEN cover_type = 'manual' THEN NULL ELSE cover_file_id END,
    cover_type = CASE WHEN cover_type = 'manual' THEN 'default' ELSE cover_type END,
    updated_at = now()
WHERE family_id = $1
  AND record_date = $2
  AND manual_cover_file_id IS NOT NULL
`

type ClearFamilyDailyManualCoverParams struct {
	FamilyID   string      `json:"familyId"`
	RecordDate pgtype.Date `json:"recordDate"`
}

func (q *Queries) ClearFamilyDailyManualCover(ctx context.Context, arg ClearFamilyDailyManualCoverParams) error {
	_, err := q.db.Exec(ctx, clearFamilyDailyManualCover, arg.FamilyID, arg.RecordDate)
	return err
}

const clearFamilyDailyManualCoverByFileID = `-- name: ClearFamilyDailyManualCoverByFileID :exec
UPDATE family_daily_covers
SET manual_cover_file_id = NULL,
    cover_file_id = CASE WHEN cover_type = 'manual' THEN NULL ELSE cover_file_id END,
    cover_type = CASE WHEN cover_type = 'manual' THEN 'default' ELSE cover_type END,
    updated_at = now()
WHERE family_id = $1
  AND record_date = $2
  AND manual_cover_file_id = $3
`

type ClearFamilyDailyManualCoverByFileIDParams struct {
	FamilyID          string      `json:"familyId"`
	RecordDate        pgtype.Date `json:"recordDate"`
	ManualCoverFileID pgtype.Text `json:"manualCoverFileId"`
}

func (q *Queries) ClearFamilyDailyManualCoverByFileID(ctx context.Context, arg ClearFamilyDailyManualCoverByFileIDParams) error {
	_, err := q.db.Exec(ctx, clearFamilyDailyManualCoverByFileID, arg.FamilyID, arg.RecordDate, arg.ManualCoverFileID)
	return err
}

const clearFamilyDailyManualCoverByFileIDs = `-- name: ClearFamilyDailyManualCoverByFileIDs :exec
UPDATE family_daily_covers
SET manual_cover_file_id = NULL,
    cover_file_id = CASE WHEN cover_type = 'manual' THEN NULL ELSE cover_file_id END,
    cover_type = CASE WHEN cover_type = 'manual' THEN 'default' ELSE cover_type END,
    updated_at = now()
WHERE family_id = $1
  AND record_date = $2
  AND manual_cover_file_id = ANY($3::text[])
`

type ClearFamilyDailyManualCoverByFileIDsParams struct {
	FamilyID   string      `json:"familyId"`
	RecordDate pgtype.Date `json:"recordDate"`
	Column3    []string    `json:"column3"`
}

func (q *Queries) ClearFamilyDailyManualCoverByFileIDs(ctx context.Context, arg ClearFamilyDailyManualCoverByFileIDsParams) error {
	_, err := q.db.Exec(ctx, clearFamilyDailyManualCoverByFileIDs, arg.FamilyID, arg.RecordDate, arg.Column3)
	return err
}

const countDiaryEntries = `-- name: CountDiaryEntries :one
SELECT COUNT(*)
FROM diary_entries de
JOIN diaries d ON d.id = de.diary_id
WHERE d.user_id = ANY($1::text[])
  AND d.record_date = $2::date
`

type CountDiaryEntriesParams struct {
	Column1 []string    `json:"column1"`
	Column2 pgtype.Date `json:"column2"`
}

func (q *Queries) CountDiaryEntries(ctx context.Context, arg CountDiaryEntriesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countDiaryEntries, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDiaryEntriesByUsers = `-- name: CountDiaryEntriesByUsers :one
SELECT COUNT(*)
FROM diary_entries
WHERE diary_id IN (SELECT id FROM diaries WHERE user_id = ANY($1::text[]))
`

func (q *Queries) CountDiaryEntriesByUsers(ctx context.Context, dollar_1 []string) (int64, error) {
	row := q.db.QueryRow(ctx, countDiaryEntriesByUsers, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWeeklyDiaryEntriesByUsers = `-- name: CountWeeklyDiaryEntriesByUsers :one
SELECT COUNT(*)
FROM diary_entries de
JOIN diaries d ON d.id = de.diary_id
WHERE d.user_id = ANY($1::text[])
  AND d.record_date >= $2::date
`

type CountWeeklyDiaryEntriesByUsersParams struct {
	Column1 []string    `json:"column1"`
	Column2 pgtype.Date `json:"column2"`
}

func (q *Queries) CountWeeklyDiaryEntriesByUsers(ctx context.Context, arg CountWeeklyDiaryEntriesByUsersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countWeeklyDiaryEntriesByUsers, arg.Column1, arg.Column2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDiaryEntriesByDiaryID = `-- name: DeleteDiaryEntriesByDiaryID :execrows
DELETE FROM diary_entries WHERE diary_id = $1
`

func (q *Queries) DeleteDiaryEntriesByDiaryID(ctx context.Context, diaryID string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDiaryEntriesByDiaryID, diaryID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDiaryIfEmpty = `-- name: DeleteDiaryIfEmpty :execrows
DELETE FROM diaries AS d
WHERE d.id = $1
  AND NOT EXISTS (SELECT 1 FROM diary_entries e WHERE e.diary_id = d.id)
  AND NOT EXISTS (SELECT 1 FROM memories m WHERE m.user_id = d.user_id AND m.record_date = d.record_date)
`

// 条件删除：头行 FOR UPDATE（LockDiaryByIDForUpdate）与本语句配合，
// 与并发新增条目（FK KEY SHARE）串行化，关闭「计数后删行」窗口内
// 并发已提交条目被级联删除的丢失路径（docs/OBJECTIVES A1）。
func (q *Queries) DeleteDiaryIfEmpty(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDiaryIfEmpty, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteDiaryImagesReturningFileIDs = `-- name: DeleteDiaryImagesReturningFileIDs :many
DELETE FROM diary_entry_images
WHERE diary_entry_id IN (SELECT id FROM diary_entries WHERE diary_id = $1)
RETURNING file_id
`

// 先删图片关联并返回 file_id，再由调用方在同一事务内删除日记（级联删除条目）。
// 拆成两条语句：PostgreSQL 不保证同一 WITH 内多个数据修改 CTE 的执行顺序，
// 若级联（删日记）先于显式 DELETE...RETURNING 执行，file_id 会为空导致文件漏清理。
func (q *Queries) DeleteDiaryImagesReturningFileIDs(ctx context.Context, diaryID string) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteDiaryImagesReturningFileIDs, diaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var file_id string
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteTrajectoryCovers = `-- name: DeleteTrajectoryCovers :exec
DELETE FROM files
WHERE file_type = 'system'
  AND metadata->>'family_id' = $1::text
  AND metadata->>'record_date' = $2::text
  AND id <> $3::text
`

type DeleteTrajectoryCoversParams struct {
	Column1 string `json:"column1"`
	Column2 string `json:"column2"`
	Column3 string `json:"column3"`
}

func (q *Queries) DeleteTrajectoryCovers(ctx context.Context, arg DeleteTrajectoryCoversParams) error {
	_, err := q.db.Exec(ctx, deleteTrajectoryCovers, arg.Column1, arg.Column2, arg.Column3)
	return err
}

const findTrajectoryCovers = `-- name: FindTrajectoryCovers :many
SELECT id, path, storage_type FROM files
WHERE file_type = 'system'
  AND metadata->>'family_id' = $1::text
  AND metadata->>'record_date' = $2::text
`

type FindTrajectoryCoversParams struct {
	Column1 string `json:"column1"`
	Column2 string `json:"column2"`
}

type FindTrajectoryCoversRow struct {
	ID          string `json:"id"`
	Path        string `json:"path"`
	StorageType string `json:"storageType"`
}

func (q *Queries) FindTrajectoryCovers(ctx context.Context, arg FindTrajectoryCoversParams) ([]FindTrajectoryCoversRow, error) {
	rows, err := q.db.Query(ctx, findTrajectoryCovers, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []FindTrajectoryCoversRow{}
	for rows.Next() {
		var i FindTrajectoryCoversRow
		if err := rows.Scan(&i.ID, &i.Path, &i.StorageType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiaryByID = `-- name: GetDiaryByID :one
SELECT id, user_id, record_date, created_at, updated_at FROM diaries WHERE id = $1
`

func (q *Queries) GetDiaryByID(ctx context.Context, id string) (Diary, error) {
	row := q.db.QueryRow(ctx, getDiaryByID, id)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecordDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiaryByUserAndDate = `-- name: GetDiaryByUserAndDate :one
SELECT id, user_id, record_date, created_at, updated_at FROM diaries WHERE user_id = $1 AND record_date = $2
`

type GetDiaryByUserAndDateParams struct {
	UserID     string      `json:"userId"`
	RecordDate pgtype.Date `json:"recordDate"`
}

func (q *Queries) GetDiaryByUserAndDate(ctx context.Context, arg GetDiaryByUserAndDateParams) (Diary, error) {
	row := q.db.QueryRow(ctx, getDiaryByUserAndDate, arg.UserID, arg.RecordDate)
	var i Diary
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RecordDate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDiaryEntriesByImageID = `-- name: GetDiaryEntriesByImageID :many
SELECT 1 AS ref
FROM diary_entries de
JOIN diary_entry_images dei ON dei.diary_entry_id = de.id
WHERE dei.file_id = $1
  AND de.id <> $2::text
LIMIT 1
`

type GetDiaryEntriesByImageIDParams struct {
	FileID       string `json:"fileId"`
	DiaryEntryID string `json:"diaryEntryId"`
}

func (q *Queries) GetDiaryEntriesByImageID(ctx context.Context, arg GetDiaryEntriesByImageIDParams) ([]int32, error) {
	rows, err := q.db.Query(ctx, getDiaryEntriesByImageID, arg.FileID, arg.DiaryEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int32{}
	for rows.Next() {
		var ref int32
		if err := rows.Scan(&ref); err != nil {
			return nil, err
		}
		items = append(items, ref)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiaryFirstRecordDate = `-- name: GetDiaryFirstRecordDate :one
SELECT COALESCE(MIN(record_date), '1970-01-01')::date AS first_record_date
FROM diaries
WHERE user_id = ANY($1::text[])
`

func (q *Queries) GetDiaryFirstRecordDate(ctx context.Context, dollar_1 []string) (pgtype.Date, error) {
	row := q.db.QueryRow(ctx, getDiaryFirstRecordDate, dollar_1)
	var first_record_date pgtype.Date
	err := row.Scan(&first_record_date)
	return first_record_date, err
}

const getFamilyDailyCover = `-- name: GetFamilyDailyCover :one
SELECT fdc.cover_file_id, fdc.cover_type, fdc.manual_cover_file_id, f.path AS cover_path, f.storage_type AS cover_storage_type
FROM family_daily_covers fdc
LEFT JOIN files f ON f.id = fdc.cover_file_id
WHERE fdc.family_id = $1 AND fdc.record_date = $2
`

type GetFamilyDailyCoverParams struct {
	FamilyID   string      `json:"familyId"`
	RecordDate pgtype.Date `json:"recordDate"`
}

type GetFamilyDailyCoverRow struct {
	CoverFileID       pgtype.Text `json:"coverFileId"`
	CoverType         string      `json:"coverType"`
	ManualCoverFileID pgtype.Text `json:"manualCoverFileId"`
	CoverPath         pgtype.Text `json:"coverPath"`
	CoverStorageType  pgtype.Text `json:"coverStorageType"`
}

func (q *Queries) GetFamilyDailyCover(ctx context.Context, arg GetFamilyDailyCoverParams) (GetFamilyDailyCoverRow, error) {
	row := q.db.QueryRow(ctx, getFamilyDailyCover, arg.FamilyID, arg.RecordDate)
	var i GetFamilyDailyCoverRow
	err := row.Scan(
		&i.CoverFileID,
		&i.CoverType,
		&i.ManualCoverFileID,
		&i.CoverPath,
		&i.CoverStorageType,
	)
	return i, err
}

const getLatestImageEntry = `-- name: GetLatestImageEntry :one
SELECT dei.file_id AS image_id, f.path, f.storage_type
FROM diary_entry_images dei
JOIN diary_entries de ON de.id = dei.diary_entry_id
JOIN diaries d ON d.id = de.diary_id
JOIN files f ON f.id = dei.file_id
WHERE d.user_id = ANY($1::text[])
  AND d.record_date = $2::date
ORDER BY dei.sort_order ASC, de.record_time DESC NULLS LAST, dei.created_at DESC
LIMIT 1
`

type GetLatestImageEntryParams struct {
	Column1 []string    `json:"column1"`
	Column2 pgtype.Date `json:"column2"`
}

type GetLatestImageEntryRow struct {
	ImageID     string `json:"imageId"`
	Path        string `json:"path"`
	StorageType string `json:"storageType"`
}

// 选择当日最新图片日记作为 image 优先级封面。
// 排序语义：用户手动排序（sort_order 越小越靠前） > 日记记录时间 > 图片上传时间。
func (q *Queries) GetLatestImageEntry(ctx context.Context, arg GetLatestImageEntryParams) (GetLatestImageEntryRow, error) {
	row := q.db.QueryRow(ctx, getLatestImageEntry, arg.Column1, arg.Column2)
	var i GetLatestImageEntryRow
	err := row.Scan(&i.ImageID, &i.Path, &i.StorageType)
	return i, err
}

const isImageUsedByFamilyDate = `-- name: IsImageUsedByFamilyDate :one
SELECT EXISTS (
    SELECT 1
    FROM diary_entry_images dei
    JOIN diary_entries de ON de.id = dei.diary_entry_id
    JOIN diaries d ON d.id = de.diary_id
    WHERE dei.file_id = $1
      AND d.user_id = ANY($2::text[])
      AND d.record_date = $3::date
)
`

type IsImageUsedByFamilyDateParams struct {
	FileID  string      `json:"fileId"`
	Column2 []string    `json:"column2"`
	Column3 pgtype.Date `json:"column3"`
}

func (q *Queries) IsImageUsedByFamilyDate(ctx context.Context, arg IsImageUsedByFamilyDateParams) (bool, error) {
	row := q.db.QueryRow(ctx, isImageUsedByFamilyDate, arg.FileID, arg.Column2, arg.Column3)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listAddressEntriesByDates = `-- name: ListAddressEntriesByDates :many
SELECT de.created_by, de.address, de.record_time, d.record_date
FROM diary_entries de
JOIN diaries d ON d.id = de.diary_id
WHERE d.user_id = ANY($1::text[])
  AND d.record_date = ANY($2::date[])
  AND de.address IS NOT NULL
  AND de.address != ''
ORDER BY d.record_date, de.record_time ASC NULLS LAST, de.created_at ASC
LIMIT 1000
`

type ListAddressEntriesByDatesParams struct {
	Column1 []string      `json:"column1"`
	Column2 []pgtype.Date `json:"column2"`
}

type ListAddressEntriesByDatesRow struct {
	CreatedBy  string             `json:"createdBy"`
	Address    pgtype.Text        `json:"address"`
	RecordTime pgtype.Timestamptz `json:"recordTime"`
	RecordDate pgtype.Date        `json:"recordDate"`
}

func (q *Queries) ListAddressEntriesByDates(ctx context.Context, arg ListAddressEntriesByDatesParams) ([]ListAddressEntriesByDatesRow, error) {
	rows, err := q.db.Query(ctx, listAddressEntriesByDates, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAddressEntriesByDatesRow{}
	for rows.Next() {
		var i ListAddressEntriesByDatesRow
		if err := rows.Scan(
			&i.CreatedBy,
			&i.Address,
			&i.RecordTime,
			&i.RecordDate,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiaryCards = `-- name: ListDiaryCards :many
WITH distinct_dates AS MATERIALIZED (
    SELECT DISTINCT record_date
    FROM diaries
    WHERE user_id = ANY($1::text[]) AND record_date < $2::date
    ORDER BY record_date DESC
    LIMIT $3
)
SELECT d.id, d.record_date, d.user_id, COUNT(de.id) AS entry_count
FROM diaries d
JOIN distinct_dates dd ON d.record_date = dd.record_date
LEFT JOIN diary_entries de ON de.diary_id = d.id
WHERE d.user_id = ANY($1::text[])
GROUP BY d.id, d.record_date, d.user_id
ORDER BY d.record_date DESC, d.user_id ASC
`

type ListDiaryCardsParams struct {
	Column1 []string    `json:"column1"`
	Column2 pgtype.Date `json:"column2"`
	Limit   int32       `json:"limit"`
}

type ListDiaryCardsRow struct {
	ID         string      `json:"id"`
	RecordDate pgtype.Date `json:"recordDate"`
	UserID     string      `json:"userId"`
	EntryCount int64       `json:"entryCount"`
}

func (q *Queries) ListDiaryCards(ctx context.Context, arg ListDiaryCardsParams) ([]ListDiaryCardsRow, error) {
	rows, err := q.db.Query(ctx, listDiaryCards, arg.Column1, arg.Column2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiaryCardsRow{}
	for rows.Next() {
		var i ListDiaryCardsRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordDate,
			&i.UserID,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiaryCardsByDates = `-- name: ListDiaryCardsByDates :many
SELECT d.id, d.record_date, d.user_id, COUNT(de.id) AS entry_count
FROM diaries d
LEFT JOIN diary_entries de ON de.diary_id = d.id
WHERE d.user_id = ANY($1::text[])
  AND d.record_date = ANY($2::date[])
GROUP BY d.id, d.record_date, d.user_id
ORDER BY d.record_date DESC, d.user_id ASC
LIMIT 1000
`

type ListDiaryCardsByDatesParams struct {
	Column1 []string      `json:"column1"`
	Column2 []pgtype.Date `json:"column2"`
}

type ListDiaryCardsByDatesRow struct {
	ID         string      `json:"id"`
	RecordDate pgtype.Date `json:"recordDate"`
	UserID     string      `json:"userId"`
	EntryCount int64       `json:"entryCount"`
}

func (q *Queries) ListDiaryCardsByDates(ctx context.Context, arg ListDiaryCardsByDatesParams) ([]ListDiaryCardsByDatesRow, error) {
	rows, err := q.db.Query(ctx, listDiaryCardsByDates, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiaryCardsByDatesRow{}
	for rows.Next() {
		var i ListDiaryCardsByDatesRow
		if err := rows.Scan(
			&i.ID,
			&i.RecordDate,
			&i.UserID,
			&i.EntryCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiaryEntries = `-- name: ListDiaryEntries :many
SELECT de.id, de.diary_id, de.created_by, de.text, de.lat, de.lon, de.address, de.detail_address, de.record_time, de.sort, de.color, de.created_at, de.updated_at, u.avatar AS user_avatar, u.nickname AS user_nickname
FROM diary_entries de
JOIN diaries d ON d.id = de.diary_id
JOIN users u ON u.id = de.created_by
WHERE d.user_id = ANY($1::text[])
  AND d.record_date = $2::date
ORDER BY de.sort ASC, de.record_time ASC NULLS LAST, de.created_at ASC
LIMIT $4 OFFSET $3
`

type ListDiaryEntriesParams struct {
	Column1 []string    `json:"column1"`
	Column2 pgtype.Date `json:"column2"`
	Offset  int32       `json:"offset"`
	Limit   int32       `json:"limit"`
}

type ListDiaryEntriesRow struct {
	ID            string             `json:"id"`
	DiaryID       string             `json:"diaryId"`
	CreatedBy     string             `json:"createdBy"`
	Text          pgtype.Text        `json:"text"`
	Lat           pgtype.Numeric     `json:"lat"`
	Lon           pgtype.Numeric     `json:"lon"`
	Address       pgtype.Text        `json:"address"`
	DetailAddress pgtype.Text        `json:"detailAddress"`
	RecordTime    pgtype.Timestamptz `json:"recordTime"`
	Sort          int32              `json:"sort"`
	Color         pgtype.Text        `json:"color"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
	UserAvatar    pgtype.Text        `json:"userAvatar"`
	UserNickname  pgtype.Text        `json:"userNickname"`
}

func (q *Queries) ListDiaryEntries(ctx context.Context, arg ListDiaryEntriesParams) ([]ListDiaryEntriesRow, error) {
	rows, err := q.db.Query(ctx, listDiaryEntries,
		arg.Column1,
		arg.Column2,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiaryEntriesRow{}
	for rows.Next() {
		var i ListDiaryEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.DiaryID,
			&i.CreatedBy,
			&i.Text,
			&i.Lat,
			&i.Lon,
			&i.Address,
			&i.DetailAddress,
			&i.RecordTime,
			&i.Sort,
			&i.Color,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.UserAvatar,
			&i.UserNickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFamilyDailyCovers = `-- name: ListFamilyDailyCovers :many
SELECT fdc.record_date, fdc.cover_type, fdc.cover_file_id, fdc.manual_cover_file_id, f.path AS cover_path, f.storage_type AS cover_storage_type
FROM family_daily_covers fdc
LEFT JOIN files f ON f.id = fdc.cover_file_id
WHERE fdc.family_id = $1 AND fdc.record_date = ANY($2::date[])
`

type ListFamilyDailyCoversParams struct {
	FamilyID    string        `json:"familyId"`
	RecordDates []pgtype.Date `json:"recordDates"`
}

type ListFamilyDailyCoversRow struct {
	RecordDate        pgtype.Date `json:"recordDate"`
	CoverType         string      `json:"coverType"`
	CoverFileID       pgtype.Text `json:"coverFileId"`
	ManualCoverFileID pgtype.Text `json:"manualCoverFileId"`
	CoverPath         pgtype.Text `json:"coverPath"`
	CoverStorageType  pgtype.Text `json:"coverStorageType"`
}

func (q *Queries) ListFamilyDailyCovers(ctx context.Context, arg ListFamilyDailyCoversParams) ([]ListFamilyDailyCoversRow, error) {
	rows, err := q.db.Query(ctx, listFamilyDailyCovers, arg.FamilyID, arg.RecordDates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFamilyDailyCoversRow{}
	for rows.Next() {
		var i ListFamilyDailyCoversRow
		if err := rows.Scan(
			&i.RecordDate,
			&i.CoverType,
			&i.CoverFileID,
			&i.ManualCoverFileID,
			&i.CoverPath,
			&i.CoverStorageType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocationEntries = `-- name: ListLocationEntries :many
SELECT de.created_by, de.lat, de.lon, de.record_time, de.created_at
FROM diary_entries de
JOIN diaries d ON d.id = de.diary_id
WHERE d.user_id = ANY($1::text[])
  AND d.record_date = $2::date
  AND de.lat IS NOT NULL
  AND de.lon IS NOT NULL
ORDER BY de.record_time ASC NULLS LAST, de.created_at ASC
LIMIT 200
`

type ListLocationEntriesParams struct {
	Column1 []string    `json:"column1"`
	Column2 pgtype.Date `json:"column2"`
}

type ListLocationEntriesRow struct {
	CreatedBy  string             `json:"createdBy"`
	Lat        pgtype.Numeric     `json:"lat"`
	Lon        pgtype.Numeric     `json:"lon"`
	RecordTime pgtype.Timestamptz `json:"recordTime"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) ListLocationEntries(ctx context.Context, arg ListLocationEntriesParams) ([]ListLocationEntriesRow, error) {
	rows, err := q.db.Query(ctx, listLocationEntries, arg.Column1, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocationEntriesRow{}
	for rows.Next() {
		var i ListLocationEntriesRow
		if err := rows.Scan(
			&i.CreatedBy,
			&i.Lat,
			&i.Lon,
			&i.RecordTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDiaryByIDForUpdate = `-- name: LockDiaryByIDForUpdate :one
SELECT id FROM diaries WHERE id = $1 FOR UPDATE
`

func (q *Queries) LockDiaryByIDForUpdate(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, lockDiaryByIDForUpdate, id)
	var id_2 string
	err := row.Scan(&id_2)
	return id_2, err
}

const setFamilyDailyManualCover = `-- name: SetFamilyDailyManualCover :exec
INSERT INTO family_daily_covers (family_id, record_date, cover_file_id, cover_type, manual_cover_file_id, updated_at)
VALUES ($1, $2, $3, 'manual', $3, now())
ON CONFLICT (family_id, record_date)
DO UPDATE SET
    cover_file_id = EXCLUDED.cover_file_id,
    cover_type = 'manual',
    manual_cover_file_id = EXCLUDED.manual_cover_file_id,
    updated_at = now()
`

type SetFamilyDailyManualCoverParams struct {
	FamilyID    string      `json:"familyId"`
	RecordDate  pgtype.Date `json:"recordDate"`
	CoverFileID pgtype.Text `json:"coverFileId"`
}

func (q *Queries) SetFamilyDailyManualCover(ctx context.Context, arg SetFamilyDailyManualCoverParams) error {
	_, err := q.db.Exec(ctx, setFamilyDailyManualCover, arg.FamilyID, arg.RecordDate, arg.CoverFileID)
	return err
}

const touchDiaryUpdatedAt = `-- name: TouchDiaryUpdatedAt :exec
UPDATE diaries SET updated_at = now() WHERE id = $1
`

func (q *Queries) TouchDiaryUpdatedAt(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchDiaryUpdatedAt, id)
	return err
}

const upsertDiary = `-- name: UpsertDiary :one
WITH ins AS (
    INSERT INTO diaries (id, user_id, record_date)
    VALUES ($1, $2, $3)
    ON CONFLICT (user_id, record_date) DO NOTHING
    RETURNING id
)
SELECT id FROM ins
UNION ALL
SELECT id FROM diaries WHERE user_id = $2 AND record_date = $3
LIMIT 1
`

type UpsertDiaryParams struct {
	ID         string      `json:"id"`
	UserID     string      `json:"userId"`
	RecordDate pgtype.Date `json:"recordDate"`
}

func (q *Queries) UpsertDiary(ctx context.Context, arg UpsertDiaryParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertDiary, arg.ID, arg.UserID, arg.RecordDate)
	var id string
	err := row.Scan(&id)
	return id, err
}

const upsertFamilyDailyCover = `-- name: UpsertFamilyDailyCover :exec
INSERT INTO family_daily_covers (family_id, record_date, cover_file_id, cover_type, manual_cover_file_id, updated_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (family_id, record_date)
DO UPDATE SET
    cover_file_id = EXCLUDED.cover_file_id,
    cover_type = EXCLUDED.cover_type,
    manual_cover_file_id = EXCLUDED.manual_cover_file_id,
    updated_at = now()
`

type UpsertFamilyDailyCoverParams struct {
	FamilyID          string      `json:"familyId"`
	RecordDate        pgtype.Date `json:"recordDate"`
	CoverFileID       pgtype.Text `json:"coverFileId"`
	CoverType         string      `json:"coverType"`
	ManualCoverFileID pgtype.Text `json:"manualCoverFileId"`
}

func (q *Queries) UpsertFamilyDailyCover(ctx context.Context, arg UpsertFamilyDailyCoverParams) error {
	_, err := q.db.Exec(ctx, upsertFamilyDailyCover,
		arg.FamilyID,
		arg.RecordDate,
		arg.CoverFileID,
		arg.CoverType,
		arg.ManualCoverFileID,
	)
	return err
}
