// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: diary_entry.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchCreateDiaryEntryImages = `-- name: BatchCreateDiaryEntryImages :exec
INSERT INTO diary_entry_images (id, diary_entry_id, file_id, sort_order, created_at)
SELECT unnest($1::text[]), $2, unnest($3::text[]), unnest($4::int[]), now()
`

type BatchCreateDiaryEntryImagesParams struct {
	Ids          []string `json:"ids"`
	DiaryEntryID string   `json:"diaryEntryId"`
	FileIds      []string `json:"fileIds"`
	SortOrders   []int32  `json:"sortOrders"`
}

func (q *Queries) BatchCreateDiaryEntryImages(ctx context.Context, arg BatchCreateDiaryEntryImagesParams) error {
	_, err := q.db.Exec(ctx, batchCreateDiaryEntryImages,
		arg.Ids,
		arg.DiaryEntryID,
		arg.FileIds,
		arg.SortOrders,
	)
	return err
}

const createAutoRecordEntry = `-- name: CreateAutoRecordEntry :exec
INSERT INTO diary_entries (
    id, diary_id, created_by, text, lat, lon, address, detail_address,
    record_time, sort, color, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now(), now())
ON CONFLICT (id) DO NOTHING
`

type CreateAutoRecordEntryParams struct {
	ID            string             `json:"id"`
	DiaryID       string             `json:"diaryId"`
	CreatedBy     string             `json:"createdBy"`
	Text          pgtype.Text        `json:"text"`
	Lat           pgtype.Numeric     `json:"lat"`
	Lon           pgtype.Numeric     `json:"lon"`
	Address       pgtype.Text        `json:"address"`
	DetailAddress pgtype.Text        `json:"detailAddress"`
	RecordTime    pgtype.Timestamptz `json:"recordTime"`
	Sort          int32              `json:"sort"`
	Color         pgtype.Text        `json:"color"`
}

func (q *Queries) CreateAutoRecordEntry(ctx context.Context, arg CreateAutoRecordEntryParams) error {
	_, err := q.db.Exec(ctx, createAutoRecordEntry,
		arg.ID,
		arg.DiaryID,
		arg.CreatedBy,
		arg.Text,
		arg.Lat,
		arg.Lon,
		arg.Address,
		arg.DetailAddress,
		arg.RecordTime,
		arg.Sort,
		arg.Color,
	)
	return err
}

const createDiaryEntry = `-- name: CreateDiaryEntry :one
INSERT INTO diary_entries (
    id, diary_id, created_by, text, lat, lon, address, detail_address,
    record_time, sort, color, created_at, updated_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, now(), now())
RETURNING id, diary_id, created_by, text, lat, lon, address, detail_address, record_time, sort, color, created_at, updated_at
`

type CreateDiaryEntryParams struct {
	ID            string             `json:"id"`
	DiaryID       string             `json:"diaryId"`
	CreatedBy     string             `json:"createdBy"`
	Text          pgtype.Text        `json:"text"`
	Lat           pgtype.Numeric     `json:"lat"`
	Lon           pgtype.Numeric     `json:"lon"`
	Address       pgtype.Text        `json:"address"`
	DetailAddress pgtype.Text        `json:"detailAddress"`
	RecordTime    pgtype.Timestamptz `json:"recordTime"`
	Sort          int32              `json:"sort"`
	Color         pgtype.Text        `json:"color"`
}

func (q *Queries) CreateDiaryEntry(ctx context.Context, arg CreateDiaryEntryParams) (DiaryEntry, error) {
	row := q.db.QueryRow(ctx, createDiaryEntry,
		arg.ID,
		arg.DiaryID,
		arg.CreatedBy,
		arg.Text,
		arg.Lat,
		arg.Lon,
		arg.Address,
		arg.DetailAddress,
		arg.RecordTime,
		arg.Sort,
		arg.Color,
	)
	var i DiaryEntry
	err := row.Scan(
		&i.ID,
		&i.DiaryID,
		&i.CreatedBy,
		&i.Text,
		&i.Lat,
		&i.Lon,
		&i.Address,
		&i.DetailAddress,
		&i.RecordTime,
		&i.Sort,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDiaryEntryImage = `-- name: CreateDiaryEntryImage :exec
INSERT INTO diary_entry_images (id, diary_entry_id, file_id, sort_order, created_at)
VALUES ($1, $2, $3, $4, now())
`

type CreateDiaryEntryImageParams struct {
	ID           string `json:"id"`
	DiaryEntryID string `json:"diaryEntryId"`
	FileID       string `json:"fileId"`
	SortOrder    int32  `json:"sortOrder"`
}

func (q *Queries) CreateDiaryEntryImage(ctx context.Context, arg CreateDiaryEntryImageParams) error {
	_, err := q.db.Exec(ctx, createDiaryEntryImage,
		arg.ID,
		arg.DiaryEntryID,
		arg.FileID,
		arg.SortOrder,
	)
	return err
}

const deleteDiaryEntryByID = `-- name: DeleteDiaryEntryByID :exec
DELETE FROM diary_entries WHERE id = $1
`

func (q *Queries) DeleteDiaryEntryByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteDiaryEntryByID, id)
	return err
}

const deleteDiaryEntryImages = `-- name: DeleteDiaryEntryImages :exec
DELETE FROM diary_entry_images WHERE diary_entry_id = $1
`

func (q *Queries) DeleteDiaryEntryImages(ctx context.Context, diaryEntryID string) error {
	_, err := q.db.Exec(ctx, deleteDiaryEntryImages, diaryEntryID)
	return err
}

const deleteDiaryEntryImagesReturningFileIDs = `-- name: DeleteDiaryEntryImagesReturningFileIDs :many
DELETE FROM diary_entry_images WHERE diary_entry_id = $1
RETURNING file_id
`

// 先删图片关联并返回 file_id，再由调用方在同一事务内删除条目。
// 拆成两条语句，避免数据修改 CTE 顺序不可预测导致 file_id 漏返回。
func (q *Queries) DeleteDiaryEntryImagesReturningFileIDs(ctx context.Context, diaryEntryID string) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteDiaryEntryImagesReturningFileIDs, diaryEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var file_id string
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDiaryEntry = `-- name: GetDiaryEntry :one
SELECT id, diary_id, created_by, text, lat, lon, address, detail_address, record_time, sort, color, created_at, updated_at FROM diary_entries WHERE id = $1
`

func (q *Queries) GetDiaryEntry(ctx context.Context, id string) (DiaryEntry, error) {
	row := q.db.QueryRow(ctx, getDiaryEntry, id)
	var i DiaryEntry
	err := row.Scan(
		&i.ID,
		&i.DiaryID,
		&i.CreatedBy,
		&i.Text,
		&i.Lat,
		&i.Lon,
		&i.Address,
		&i.DetailAddress,
		&i.RecordTime,
		&i.Sort,
		&i.Color,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAutoEntryAddressesByDate = `-- name: ListAutoEntryAddressesByDate :many
SELECT e.id, e.address, e.detail_address
FROM diary_entries e
JOIN diaries d ON d.id = e.diary_id
WHERE e.created_by = $1
  AND e.text = '（自动记录）'
  AND d.record_date = $2
ORDER BY e.record_time DESC NULLS LAST
`

type ListAutoEntryAddressesByDateParams struct {
	CreatedBy  string      `json:"createdBy"`
	RecordDate pgtype.Date `json:"recordDate"`
}

type ListAutoEntryAddressesByDateRow struct {
	ID            string      `json:"id"`
	Address       pgtype.Text `json:"address"`
	DetailAddress pgtype.Text `json:"detailAddress"`
}

// R-20/R-22（同日去重集合化）：取当天全部自动条目的 id+地址，后台与手动即时成文共用；
// 后者需要已存在条目 id 供响应契约（ORDER BY DESC 保证首条命中即最新）。
func (q *Queries) ListAutoEntryAddressesByDate(ctx context.Context, arg ListAutoEntryAddressesByDateParams) ([]ListAutoEntryAddressesByDateRow, error) {
	rows, err := q.db.Query(ctx, listAutoEntryAddressesByDate, arg.CreatedBy, arg.RecordDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAutoEntryAddressesByDateRow{}
	for rows.Next() {
		var i ListAutoEntryAddressesByDateRow
		if err := rows.Scan(&i.ID, &i.Address, &i.DetailAddress); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiaryEntryImageFileIDsByDiaryID = `-- name: ListDiaryEntryImageFileIDsByDiaryID :many
SELECT DISTINCT dei.file_id
FROM diary_entry_images dei
JOIN diary_entries de ON de.id = dei.diary_entry_id
WHERE de.diary_id = $1
`

func (q *Queries) ListDiaryEntryImageFileIDsByDiaryID(ctx context.Context, diaryID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDiaryEntryImageFileIDsByDiaryID, diaryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var file_id string
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiaryEntryImagePaths = `-- name: ListDiaryEntryImagePaths :many
SELECT dei.file_id, f.path, f.storage_type
FROM diary_entry_images dei
JOIN files f ON f.id = dei.file_id
WHERE dei.diary_entry_id = $1
ORDER BY dei.sort_order ASC, dei.created_at ASC
`

type ListDiaryEntryImagePathsRow struct {
	FileID      string `json:"fileId"`
	Path        string `json:"path"`
	StorageType string `json:"storageType"`
}

func (q *Queries) ListDiaryEntryImagePaths(ctx context.Context, diaryEntryID string) ([]ListDiaryEntryImagePathsRow, error) {
	rows, err := q.db.Query(ctx, listDiaryEntryImagePaths, diaryEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiaryEntryImagePathsRow{}
	for rows.Next() {
		var i ListDiaryEntryImagePathsRow
		if err := rows.Scan(&i.FileID, &i.Path, &i.StorageType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiaryEntryImagePathsByEntryIDs = `-- name: ListDiaryEntryImagePathsByEntryIDs :many
SELECT dei.diary_entry_id, dei.file_id, f.path, f.storage_type
FROM diary_entry_images dei
JOIN files f ON f.id = dei.file_id
WHERE dei.diary_entry_id = ANY($1::text[])
ORDER BY dei.diary_entry_id, dei.sort_order ASC, dei.created_at ASC
`

type ListDiaryEntryImagePathsByEntryIDsRow struct {
	DiaryEntryID string `json:"diaryEntryId"`
	FileID       string `json:"fileId"`
	Path         string `json:"path"`
	StorageType  string `json:"storageType"`
}

func (q *Queries) ListDiaryEntryImagePathsByEntryIDs(ctx context.Context, dollar_1 []string) ([]ListDiaryEntryImagePathsByEntryIDsRow, error) {
	rows, err := q.db.Query(ctx, listDiaryEntryImagePathsByEntryIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDiaryEntryImagePathsByEntryIDsRow{}
	for rows.Next() {
		var i ListDiaryEntryImagePathsByEntryIDsRow
		if err := rows.Scan(
			&i.DiaryEntryID,
			&i.FileID,
			&i.Path,
			&i.StorageType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDiaryEntryImages = `-- name: ListDiaryEntryImages :many
SELECT file_id FROM diary_entry_images
WHERE diary_entry_id = $1
ORDER BY sort_order ASC, created_at ASC
`

func (q *Queries) ListDiaryEntryImages(ctx context.Context, diaryEntryID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listDiaryEntryImages, diaryEntryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var file_id string
		if err := rows.Scan(&file_id); err != nil {
			return nil, err
		}
		items = append(items, file_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDiaryEntry = `-- name: UpdateDiaryEntry :execrows
UPDATE diary_entries SET
    text = $2,
    lat = $3,
    lon = $4,
    address = $5,
    detail_address = $6,
    record_time = $7,
    sort = $8,
    color = $9,
    updated_at = now()
WHERE id = $1
`

type UpdateDiaryEntryParams struct {
	ID            string             `json:"id"`
	Text          pgtype.Text        `json:"text"`
	Lat           pgtype.Numeric     `json:"lat"`
	Lon           pgtype.Numeric     `json:"lon"`
	Address       pgtype.Text        `json:"address"`
	DetailAddress pgtype.Text        `json:"detailAddress"`
	RecordTime    pgtype.Timestamptz `json:"recordTime"`
	Sort          int32              `json:"sort"`
	Color         pgtype.Text        `json:"color"`
}

func (q *Queries) UpdateDiaryEntry(ctx context.Context, arg UpdateDiaryEntryParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDiaryEntry,
		arg.ID,
		arg.Text,
		arg.Lat,
		arg.Lon,
		arg.Address,
		arg.DetailAddress,
		arg.RecordTime,
		arg.Sort,
		arg.Color,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
