// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: family.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchMigrateUsersDailyCoversToPersonal = `-- name: BatchMigrateUsersDailyCoversToPersonal :exec
WITH pairs AS (
    SELECT unnest($2::text[]) AS user_id, unnest($3::text[]) AS personal_family_id
)
INSERT INTO family_daily_covers (
    family_id,
    record_date,
    cover_file_id,
    cover_type,
    manual_cover_file_id,
    updated_at
)
SELECT
    p.personal_family_id,
    src.record_date,
    src.cover_file_id,
    src.cover_type,
    src.manual_cover_file_id,
    src.updated_at
FROM family_daily_covers src
JOIN pairs p ON true
JOIN diaries d ON d.user_id = p.user_id AND d.record_date = src.record_date
WHERE src.family_id = $1
  AND src.cover_type != 'default'
ON CONFLICT (family_id, record_date)
DO UPDATE SET
    cover_file_id = EXCLUDED.cover_file_id,
    cover_type = EXCLUDED.cover_type,
    manual_cover_file_id = EXCLUDED.manual_cover_file_id,
    updated_at = EXCLUDED.updated_at
WHERE family_daily_covers.cover_type = 'default'
`

type BatchMigrateUsersDailyCoversToPersonalParams struct {
	SourceFamilyID    string   `json:"sourceFamilyId"`
	UserIds           []string `json:"userIds"`
	PersonalFamilyIds []string `json:"personalFamilyIds"`
}

func (q *Queries) BatchMigrateUsersDailyCoversToPersonal(ctx context.Context, arg BatchMigrateUsersDailyCoversToPersonalParams) error {
	_, err := q.db.Exec(ctx, batchMigrateUsersDailyCoversToPersonal, arg.SourceFamilyID, arg.UserIds, arg.PersonalFamilyIds)
	return err
}

const batchUpsertFamilyMembership = `-- name: BatchUpsertFamilyMembership :exec
INSERT INTO family_members (id, family_id, user_id, role, joined_at)
SELECT unnest($1::text[]), $2, unnest($3::text[]), 'member', now()
ON CONFLICT (family_id, user_id) DO UPDATE SET
    role = EXCLUDED.role,
    joined_at = EXCLUDED.joined_at
`

type BatchUpsertFamilyMembershipParams struct {
	Ids      []string `json:"ids"`
	FamilyID string   `json:"familyId"`
	UserIds  []string `json:"userIds"`
}

func (q *Queries) BatchUpsertFamilyMembership(ctx context.Context, arg BatchUpsertFamilyMembershipParams) error {
	_, err := q.db.Exec(ctx, batchUpsertFamilyMembership, arg.Ids, arg.FamilyID, arg.UserIds)
	return err
}

const batchUpsertFamilyMembershipOwner = `-- name: BatchUpsertFamilyMembershipOwner :exec
INSERT INTO family_members (id, family_id, user_id, role, joined_at)
SELECT unnest($1::text[]), unnest($2::text[]), unnest($3::text[]), 'owner', now()
ON CONFLICT (family_id, user_id) DO UPDATE SET
    role = EXCLUDED.role,
    joined_at = EXCLUDED.joined_at
`

type BatchUpsertFamilyMembershipOwnerParams struct {
	Ids       []string `json:"ids"`
	FamilyIds []string `json:"familyIds"`
	UserIds   []string `json:"userIds"`
}

func (q *Queries) BatchUpsertFamilyMembershipOwner(ctx context.Context, arg BatchUpsertFamilyMembershipOwnerParams) error {
	_, err := q.db.Exec(ctx, batchUpsertFamilyMembershipOwner, arg.Ids, arg.FamilyIds, arg.UserIds)
	return err
}

const countFamilyDailyCovers = `-- name: CountFamilyDailyCovers :one
SELECT COUNT(*) FROM family_daily_covers WHERE family_id = $1
`

func (q *Queries) CountFamilyDailyCovers(ctx context.Context, familyID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFamilyDailyCovers, familyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countFamilyMembers = `-- name: CountFamilyMembers :one
SELECT COUNT(*) FROM family_members WHERE family_id = $1
`

func (q *Queries) CountFamilyMembers(ctx context.Context, familyID string) (int64, error) {
	row := q.db.QueryRow(ctx, countFamilyMembers, familyID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFamily = `-- name: CreateFamily :one
INSERT INTO families (id, is_personal, created_at)
VALUES ($1, $2, now())
RETURNING id
`

type CreateFamilyParams struct {
	ID         string `json:"id"`
	IsPersonal bool   `json:"isPersonal"`
}

func (q *Queries) CreateFamily(ctx context.Context, arg CreateFamilyParams) (string, error) {
	row := q.db.QueryRow(ctx, createFamily, arg.ID, arg.IsPersonal)
	var id string
	err := row.Scan(&id)
	return id, err
}

const deleteFamily = `-- name: DeleteFamily :exec
DELETE FROM families WHERE id = $1
`

func (q *Queries) DeleteFamily(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFamily, id)
	return err
}

const deleteFamilyDailyCovers = `-- name: DeleteFamilyDailyCovers :exec
DELETE FROM family_daily_covers WHERE family_id = $1
`

func (q *Queries) DeleteFamilyDailyCovers(ctx context.Context, familyID string) error {
	_, err := q.db.Exec(ctx, deleteFamilyDailyCovers, familyID)
	return err
}

const deleteFamilyMembers = `-- name: DeleteFamilyMembers :exec
DELETE FROM family_members WHERE family_id = $1
`

func (q *Queries) DeleteFamilyMembers(ctx context.Context, familyID string) error {
	_, err := q.db.Exec(ctx, deleteFamilyMembers, familyID)
	return err
}

const deleteFamilyMembership = `-- name: DeleteFamilyMembership :exec
DELETE FROM family_members WHERE family_id = $1 AND user_id = $2
`

type DeleteFamilyMembershipParams struct {
	FamilyID string `json:"familyId"`
	UserID   string `json:"userId"`
}

func (q *Queries) DeleteFamilyMembership(ctx context.Context, arg DeleteFamilyMembershipParams) error {
	_, err := q.db.Exec(ctx, deleteFamilyMembership, arg.FamilyID, arg.UserID)
	return err
}

const getFamilyByID = `-- name: GetFamilyByID :one
SELECT id, is_personal, created_at FROM families WHERE id = $1
`

type GetFamilyByIDRow struct {
	ID         string             `json:"id"`
	IsPersonal bool               `json:"isPersonal"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

func (q *Queries) GetFamilyByID(ctx context.Context, id string) (GetFamilyByIDRow, error) {
	row := q.db.QueryRow(ctx, getFamilyByID, id)
	var i GetFamilyByIDRow
	err := row.Scan(&i.ID, &i.IsPersonal, &i.CreatedAt)
	return i, err
}

const getFamilyOwner = `-- name: GetFamilyOwner :one
SELECT user_id FROM family_members WHERE family_id = $1 AND role = 'owner'
`

func (q *Queries) GetFamilyOwner(ctx context.Context, familyID string) (string, error) {
	row := q.db.QueryRow(ctx, getFamilyOwner, familyID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getFamilyRemovedMembers = `-- name: GetFamilyRemovedMembers :one
SELECT removed_members FROM families WHERE id = $1
`

func (q *Queries) GetFamilyRemovedMembers(ctx context.Context, id string) ([]byte, error) {
	row := q.db.QueryRow(ctx, getFamilyRemovedMembers, id)
	var removed_members []byte
	err := row.Scan(&removed_members)
	return removed_members, err
}

const isFamilyMember = `-- name: IsFamilyMember :one
SELECT EXISTS(SELECT 1 FROM family_members WHERE family_id = $1 AND user_id = $2)
`

type IsFamilyMemberParams struct {
	FamilyID string `json:"familyId"`
	UserID   string `json:"userId"`
}

func (q *Queries) IsFamilyMember(ctx context.Context, arg IsFamilyMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isFamilyMember, arg.FamilyID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listFamilyMemberPersonalFamilies = `-- name: ListFamilyMemberPersonalFamilies :many
SELECT u.id, u.personal_family_id
FROM family_members fm
JOIN users u ON u.id = fm.user_id
WHERE fm.family_id = $1
ORDER BY fm.user_id ASC
`

type ListFamilyMemberPersonalFamiliesRow struct {
	ID               string      `json:"id"`
	PersonalFamilyID pgtype.Text `json:"personalFamilyId"`
}

func (q *Queries) ListFamilyMemberPersonalFamilies(ctx context.Context, familyID string) ([]ListFamilyMemberPersonalFamiliesRow, error) {
	rows, err := q.db.Query(ctx, listFamilyMemberPersonalFamilies, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFamilyMemberPersonalFamiliesRow{}
	for rows.Next() {
		var i ListFamilyMemberPersonalFamiliesRow
		if err := rows.Scan(&i.ID, &i.PersonalFamilyID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFamilyMembers = `-- name: ListFamilyMembers :many
SELECT
    fm.user_id,
    fm.role,
    fm.joined_at,
    u.avatar,
    u.avatar_file_id,
    u.nickname
FROM family_members fm
JOIN users u ON u.id = fm.user_id
WHERE fm.family_id = $1
ORDER BY fm.joined_at ASC, fm.user_id ASC
`

type ListFamilyMembersRow struct {
	UserID       string             `json:"userId"`
	Role         string             `json:"role"`
	JoinedAt     pgtype.Timestamptz `json:"joinedAt"`
	Avatar       pgtype.Text        `json:"avatar"`
	AvatarFileID pgtype.Text        `json:"avatarFileId"`
	Nickname     pgtype.Text        `json:"nickname"`
}

func (q *Queries) ListFamilyMembers(ctx context.Context, familyID string) ([]ListFamilyMembersRow, error) {
	rows, err := q.db.Query(ctx, listFamilyMembers, familyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFamilyMembersRow{}
	for rows.Next() {
		var i ListFamilyMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Avatar,
			&i.AvatarFileID,
			&i.Nickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFamilyMembersByUserID = `-- name: ListFamilyMembersByUserID :many
SELECT
    cur.current_family_id,
    fm.user_id,
    fm.role,
    fm.joined_at,
    mu.avatar,
    mu.avatar_file_id,
    mu.nickname
FROM users cur
LEFT JOIN family_members fm ON fm.family_id = cur.current_family_id
LEFT JOIN users mu ON mu.id = fm.user_id
WHERE cur.id = $1
ORDER BY fm.joined_at ASC, fm.user_id ASC
`

type ListFamilyMembersByUserIDRow struct {
	CurrentFamilyID pgtype.Text        `json:"currentFamilyId"`
	UserID          pgtype.Text        `json:"userId"`
	Role            pgtype.Text        `json:"role"`
	JoinedAt        pgtype.Timestamptz `json:"joinedAt"`
	Avatar          pgtype.Text        `json:"avatar"`
	AvatarFileID    pgtype.Text        `json:"avatarFileId"`
	Nickname        pgtype.Text        `json:"nickname"`
}

// 一次往返同时取用户当前家庭与其成员列表（替代 GetUserByID + ListFamilyMembers 两段串行，
// 是 diary 全部端点的公共前缀）。LEFT JOIN 保形：无家庭时返回单行全 NULL（fm.* 判空跳过），
// 用户不存在时 0 行（调用方转 ErrNoRows），与旧两查语义逐一对齐。
func (q *Queries) ListFamilyMembersByUserID(ctx context.Context, id string) ([]ListFamilyMembersByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listFamilyMembersByUserID, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFamilyMembersByUserIDRow{}
	for rows.Next() {
		var i ListFamilyMembersByUserIDRow
		if err := rows.Scan(
			&i.CurrentFamilyID,
			&i.UserID,
			&i.Role,
			&i.JoinedAt,
			&i.Avatar,
			&i.AvatarFileID,
			&i.Nickname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const migrateFamilyDailyCovers = `-- name: MigrateFamilyDailyCovers :exec
INSERT INTO family_daily_covers (
    family_id,
    record_date,
    cover_file_id,
    cover_type,
    manual_cover_file_id,
    updated_at
)
SELECT $2 AS family_id, record_date, cover_file_id, cover_type, manual_cover_file_id, updated_at
FROM family_daily_covers src
WHERE src.family_id = $1
  AND src.cover_type != 'default'
ON CONFLICT (family_id, record_date)
DO UPDATE SET
    cover_file_id = EXCLUDED.cover_file_id,
    cover_type = EXCLUDED.cover_type,
    manual_cover_file_id = EXCLUDED.manual_cover_file_id,
    updated_at = EXCLUDED.updated_at
WHERE family_daily_covers.cover_type = 'default'
`

type MigrateFamilyDailyCoversParams struct {
	FamilyID   string `json:"familyId"`
	FamilyID_2 string `json:"familyId2"`
}

func (q *Queries) MigrateFamilyDailyCovers(ctx context.Context, arg MigrateFamilyDailyCoversParams) error {
	_, err := q.db.Exec(ctx, migrateFamilyDailyCovers, arg.FamilyID, arg.FamilyID_2)
	return err
}

const migrateUserDailyCoversToFamily = `-- name: MigrateUserDailyCoversToFamily :exec
INSERT INTO family_daily_covers (
    family_id,
    record_date,
    cover_file_id,
    cover_type,
    manual_cover_file_id,
    updated_at
)
SELECT
    $3 AS family_id,
    src.record_date,
    src.cover_file_id,
    src.cover_type,
    src.manual_cover_file_id,
    src.updated_at
FROM family_daily_covers src
JOIN diaries d ON d.user_id = $2 AND d.record_date = src.record_date
WHERE src.family_id = $1
  AND src.cover_type != 'default'
ON CONFLICT (family_id, record_date)
DO UPDATE SET
    cover_file_id = EXCLUDED.cover_file_id,
    cover_type = EXCLUDED.cover_type,
    manual_cover_file_id = EXCLUDED.manual_cover_file_id,
    updated_at = EXCLUDED.updated_at
WHERE family_daily_covers.cover_type = 'default'
`

type MigrateUserDailyCoversToFamilyParams struct {
	FamilyID   string `json:"familyId"`
	UserID     string `json:"userId"`
	FamilyID_2 string `json:"familyId2"`
}

func (q *Queries) MigrateUserDailyCoversToFamily(ctx context.Context, arg MigrateUserDailyCoversToFamilyParams) error {
	_, err := q.db.Exec(ctx, migrateUserDailyCoversToFamily, arg.FamilyID, arg.UserID, arg.FamilyID_2)
	return err
}

const recordRemovedMember = `-- name: RecordRemovedMember :exec
UPDATE families
SET removed_members = COALESCE(removed_members, '{}'::jsonb) || $2::jsonb
WHERE id = $1
`

type RecordRemovedMemberParams struct {
	ID      string `json:"id"`
	Column2 []byte `json:"column2"`
}

func (q *Queries) RecordRemovedMember(ctx context.Context, arg RecordRemovedMemberParams) error {
	_, err := q.db.Exec(ctx, recordRemovedMember, arg.ID, arg.Column2)
	return err
}

const upsertFamilyMembership = `-- name: UpsertFamilyMembership :one
INSERT INTO family_members (id, family_id, user_id, role, joined_at)
VALUES ($1, $2, $3, $4, now())
ON CONFLICT (family_id, user_id) DO UPDATE SET
    role = EXCLUDED.role,
    joined_at = EXCLUDED.joined_at
RETURNING id
`

type UpsertFamilyMembershipParams struct {
	ID       string `json:"id"`
	FamilyID string `json:"familyId"`
	UserID   string `json:"userId"`
	Role     string `json:"role"`
}

func (q *Queries) UpsertFamilyMembership(ctx context.Context, arg UpsertFamilyMembershipParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertFamilyMembership,
		arg.ID,
		arg.FamilyID,
		arg.UserID,
		arg.Role,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}
