// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: file.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const batchDeleteFiles = `-- name: BatchDeleteFiles :many
DELETE FROM files
WHERE id = ANY($1::text[])
RETURNING id, path, storage_type
`

type BatchDeleteFilesRow struct {
	ID          string `json:"id"`
	Path        string `json:"path"`
	StorageType string `json:"storageType"`
}

func (q *Queries) BatchDeleteFiles(ctx context.Context, dollar_1 []string) ([]BatchDeleteFilesRow, error) {
	rows, err := q.db.Query(ctx, batchDeleteFiles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []BatchDeleteFilesRow{}
	for rows.Next() {
		var i BatchDeleteFilesRow
		if err := rows.Scan(&i.ID, &i.Path, &i.StorageType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const clearAvatarReferencesToOrphanFiles = `-- name: ClearAvatarReferencesToOrphanFiles :exec
UPDATE users u
SET avatar = NULL, avatar_file_id = NULL, updated_at = now()
WHERE u.avatar_file_id IS NOT NULL
  AND NOT EXISTS (SELECT 1 FROM files f WHERE f.id = u.avatar_file_id)
`

func (q *Queries) ClearAvatarReferencesToOrphanFiles(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearAvatarReferencesToOrphanFiles)
	return err
}

const clearTrajectoryFamilyID = `-- name: ClearTrajectoryFamilyID :exec
UPDATE files
SET metadata = metadata - 'family_id',
    updated_at = now()
WHERE file_type = 'system'
  AND metadata->>'family_id' = $1::text
`

func (q *Queries) ClearTrajectoryFamilyID(ctx context.Context, familyID string) error {
	_, err := q.db.Exec(ctx, clearTrajectoryFamilyID, familyID)
	return err
}

const clearUserAvatarByFile = `-- name: ClearUserAvatarByFile :exec
UPDATE users SET avatar = NULL, avatar_file_id = NULL, updated_at = now()
WHERE avatar_file_id = $1 AND id = $2
`

type ClearUserAvatarByFileParams struct {
	AvatarFileID pgtype.Text `json:"avatarFileId"`
	ID           string      `json:"id"`
}

func (q *Queries) ClearUserAvatarByFile(ctx context.Context, arg ClearUserAvatarByFileParams) error {
	_, err := q.db.Exec(ctx, clearUserAvatarByFile, arg.AvatarFileID, arg.ID)
	return err
}

const createFile = `-- name: CreateFile :one
INSERT INTO files (id, created_by, path, name, suffix, size_bytes, file_type, storage_type, metadata, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, now(), now())
RETURNING id, created_by, path, name, suffix, size_bytes, file_type, metadata, created_at, updated_at, storage_type
`

type CreateFileParams struct {
	ID          string      `json:"id"`
	CreatedBy   pgtype.Text `json:"createdBy"`
	Path        string      `json:"path"`
	Name        string      `json:"name"`
	Suffix      string      `json:"suffix"`
	SizeBytes   int64       `json:"sizeBytes"`
	FileType    string      `json:"fileType"`
	StorageType string      `json:"storageType"`
	Metadata    []byte      `json:"metadata"`
}

func (q *Queries) CreateFile(ctx context.Context, arg CreateFileParams) (File, error) {
	row := q.db.QueryRow(ctx, createFile,
		arg.ID,
		arg.CreatedBy,
		arg.Path,
		arg.Name,
		arg.Suffix,
		arg.SizeBytes,
		arg.FileType,
		arg.StorageType,
		arg.Metadata,
	)
	var i File
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Path,
		&i.Name,
		&i.Suffix,
		&i.SizeBytes,
		&i.FileType,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageType,
	)
	return i, err
}

const deleteFile = `-- name: DeleteFile :exec
DELETE FROM files WHERE id = $1
`

func (q *Queries) DeleteFile(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteFile, id)
	return err
}

const getFileByID = `-- name: GetFileByID :one
SELECT id, created_by, path, name, suffix, size_bytes, file_type, metadata, created_at, updated_at, storage_type FROM files WHERE id = $1
`

func (q *Queries) GetFileByID(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRow(ctx, getFileByID, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Path,
		&i.Name,
		&i.Suffix,
		&i.SizeBytes,
		&i.FileType,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageType,
	)
	return i, err
}

const getFileByIDForUpdate = `-- name: GetFileByIDForUpdate :one
SELECT id, created_by, path, name, suffix, size_bytes, file_type, metadata, created_at, updated_at, storage_type FROM files WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetFileByIDForUpdate(ctx context.Context, id string) (File, error) {
	row := q.db.QueryRow(ctx, getFileByIDForUpdate, id)
	var i File
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Path,
		&i.Name,
		&i.Suffix,
		&i.SizeBytes,
		&i.FileType,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageType,
	)
	return i, err
}

const getFileByPath = `-- name: GetFileByPath :one
SELECT id, created_by, path, name, suffix, size_bytes, file_type, metadata, created_at, updated_at, storage_type FROM files WHERE path = $1
`

func (q *Queries) GetFileByPath(ctx context.Context, path string) (File, error) {
	row := q.db.QueryRow(ctx, getFileByPath, path)
	var i File
	err := row.Scan(
		&i.ID,
		&i.CreatedBy,
		&i.Path,
		&i.Name,
		&i.Suffix,
		&i.SizeBytes,
		&i.FileType,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StorageType,
	)
	return i, err
}

const getFileReferences = `-- name: GetFileReferences :one
SELECT
    EXISTS(SELECT 1 FROM family_daily_covers WHERE cover_file_id = $1 OR manual_cover_file_id = $1) AS used_by_cover,
    EXISTS(SELECT 1 FROM diary_entry_images WHERE file_id = $1) AS used_by_entry,
    (SELECT COUNT(*) FROM users WHERE avatar_file_id = $1)::int AS avatar_user_count
`

type GetFileReferencesRow struct {
	UsedByCover     bool  `json:"usedByCover"`
	UsedByEntry     bool  `json:"usedByEntry"`
	AvatarUserCount int32 `json:"avatarUserCount"`
}

func (q *Queries) GetFileReferences(ctx context.Context, coverFileID pgtype.Text) (GetFileReferencesRow, error) {
	row := q.db.QueryRow(ctx, getFileReferences, coverFileID)
	var i GetFileReferencesRow
	err := row.Scan(&i.UsedByCover, &i.UsedByEntry, &i.AvatarUserCount)
	return i, err
}

const getFilesByIDs = `-- name: GetFilesByIDs :many
SELECT id, created_by, path, name, suffix, size_bytes, file_type, metadata, created_at, updated_at, storage_type FROM files WHERE id = ANY($1::text[])
`

func (q *Queries) GetFilesByIDs(ctx context.Context, dollar_1 []string) ([]File, error) {
	rows, err := q.db.Query(ctx, getFilesByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []File{}
	for rows.Next() {
		var i File
		if err := rows.Scan(
			&i.ID,
			&i.CreatedBy,
			&i.Path,
			&i.Name,
			&i.Suffix,
			&i.SizeBytes,
			&i.FileType,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StorageType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesByCreator = `-- name: ListFilesByCreator :many
SELECT f.id, f.path
FROM files f
WHERE f.created_by = $1
  AND f.id > $2
ORDER BY f.id ASC
LIMIT $3
`

type ListFilesByCreatorParams struct {
	CreatedBy pgtype.Text `json:"createdBy"`
	ID        string      `json:"id"`
	Limit     int32       `json:"limit"`
}

type ListFilesByCreatorRow struct {
	ID   string `json:"id"`
	Path string `json:"path"`
}

func (q *Queries) ListFilesByCreator(ctx context.Context, arg ListFilesByCreatorParams) ([]ListFilesByCreatorRow, error) {
	rows, err := q.db.Query(ctx, listFilesByCreator, arg.CreatedBy, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListFilesByCreatorRow{}
	for rows.Next() {
		var i ListFilesByCreatorRow
		if err := rows.Scan(&i.ID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanFilesByCreator = `-- name: ListOrphanFilesByCreator :many
SELECT f.id, f.path
FROM files f
WHERE f.created_by = $1
  AND f.id > $2
  AND NOT EXISTS (SELECT 1 FROM family_daily_covers fdc WHERE fdc.cover_file_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM family_daily_covers fdc2 WHERE fdc2.manual_cover_file_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM diary_entry_images dei WHERE dei.file_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM users u WHERE u.avatar_file_id = f.id)
ORDER BY f.id ASC
LIMIT $3
`

type ListOrphanFilesByCreatorParams struct {
	CreatedBy pgtype.Text `json:"createdBy"`
	ID        string      `json:"id"`
	Limit     int32       `json:"limit"`
}

type ListOrphanFilesByCreatorRow struct {
	ID   string `json:"id"`
	Path string `json:"path"`
}

func (q *Queries) ListOrphanFilesByCreator(ctx context.Context, arg ListOrphanFilesByCreatorParams) ([]ListOrphanFilesByCreatorRow, error) {
	rows, err := q.db.Query(ctx, listOrphanFilesByCreator, arg.CreatedBy, arg.ID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrphanFilesByCreatorRow{}
	for rows.Next() {
		var i ListOrphanFilesByCreatorRow
		if err := rows.Scan(&i.ID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserInviteQRCodeFiles = `-- name: ListUserInviteQRCodeFiles :many
SELECT id, path, storage_type FROM files
WHERE created_by = $1 AND file_type = 'system'
  AND metadata ? 'family_id'
  AND NOT metadata ? 'record_date'
  AND metadata->>'raw' = $2
ORDER BY id ASC
LIMIT 100
`

type ListUserInviteQRCodeFilesParams struct {
	CreatedBy pgtype.Text `json:"createdBy"`
	Metadata  []byte      `json:"metadata"`
}

type ListUserInviteQRCodeFilesRow struct {
	ID          string `json:"id"`
	Path        string `json:"path"`
	StorageType string `json:"storageType"`
}

func (q *Queries) ListUserInviteQRCodeFiles(ctx context.Context, arg ListUserInviteQRCodeFilesParams) ([]ListUserInviteQRCodeFilesRow, error) {
	rows, err := q.db.Query(ctx, listUserInviteQRCodeFiles, arg.CreatedBy, arg.Metadata)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserInviteQRCodeFilesRow{}
	for rows.Next() {
		var i ListUserInviteQRCodeFilesRow
		if err := rows.Scan(&i.ID, &i.Path, &i.StorageType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanOldSystemFiles = `-- name: ScanOldSystemFiles :many
SELECT id, path, storage_type FROM files
WHERE file_type = 'system'
  AND id > $1
  AND created_at < now() - interval '7 days'
  AND updated_at < now() - interval '7 days'
  AND NOT COALESCE(metadata ? 'raw', false)
  AND NOT EXISTS (
    SELECT 1 FROM family_daily_covers fdc
    WHERE fdc.cover_file_id = files.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM family_daily_covers fdc2
    WHERE fdc2.manual_cover_file_id = files.id
  )
  AND NOT EXISTS (
    SELECT 1 FROM user_avatar_markers uam
    WHERE uam.marker_path = files.path
  )
ORDER BY id ASC
LIMIT 1000
`

type ScanOldSystemFilesRow struct {
	ID          string `json:"id"`
	Path        string `json:"path"`
	StorageType string `json:"storageType"`
}

// 邀请二维码/分享海报豁免：invite/qrcode.go generate 写入的海报记录 metadata 恒含 'raw' 键
// （轨迹图为 {family_id, record_date}、头像 marker 为 {}，均无该键，故 'raw' 是 invite 资产唯一识别特征）。
// 已分发到微信会话的图片 URL 不能被 7 天窗口静默回收成 404；其回收由两条替代路径覆盖：
// ①重生成替换（generate 事务内删旧记录、提交后删旧物理文件）②注销清理（DeleteAccount 按
// created_by 收集全部 files 路径删物理文件）。COALESCE 兜底 metadata 为 NULL 的行维持可回收。
func (q *Queries) ScanOldSystemFiles(ctx context.Context, id string) ([]ScanOldSystemFilesRow, error) {
	rows, err := q.db.Query(ctx, scanOldSystemFiles, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanOldSystemFilesRow{}
	for rows.Next() {
		var i ScanOldSystemFilesRow
		if err := rows.Scan(&i.ID, &i.Path, &i.StorageType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const scanOrphanFiles = `-- name: ScanOrphanFiles :many
SELECT f.id, f.path
FROM files f
WHERE f.file_type = 'image'
  AND f.id > $1
  AND f.created_at < now() - interval '7 days'
  AND NOT EXISTS (SELECT 1 FROM diary_entry_images dei WHERE dei.file_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM users u WHERE u.avatar_file_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM family_daily_covers fdc WHERE fdc.cover_file_id = f.id)
  AND NOT EXISTS (SELECT 1 FROM family_daily_covers fdc2 WHERE fdc2.manual_cover_file_id = f.id)
ORDER BY f.id ASC
LIMIT 1000
`

type ScanOrphanFilesRow struct {
	ID   string `json:"id"`
	Path string `json:"path"`
}

// 宽限窗 7 天：上传成功但尚未挂到任何引用（客户端崩溃/离线草稿）的图片不应被回收，
// 与代码注释及 spec「7 天孤儿清理兜底」口径一致。
func (q *Queries) ScanOrphanFiles(ctx context.Context, id string) ([]ScanOrphanFilesRow, error) {
	rows, err := q.db.Query(ctx, scanOrphanFiles, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ScanOrphanFilesRow{}
	for rows.Next() {
		var i ScanOrphanFilesRow
		if err := rows.Scan(&i.ID, &i.Path); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
