// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: invite.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countInviterMonthlyRewardDays = `-- name: CountInviterMonthlyRewardDays :one
SELECT COALESCE(COUNT(*) * 7, 0)::int AS total_days
FROM user_invites
WHERE inviter_id = $1
  AND reward_inviter_at >= $2
  AND reward_inviter_at < $3
`

type CountInviterMonthlyRewardDaysParams struct {
	InviterID         pgtype.Text        `json:"inviterId"`
	RewardInviterAt   pgtype.Timestamptz `json:"rewardInviterAt"`
	RewardInviterAt_2 pgtype.Timestamptz `json:"rewardInviterAt2"`
}

func (q *Queries) CountInviterMonthlyRewardDays(ctx context.Context, arg CountInviterMonthlyRewardDaysParams) (int32, error) {
	row := q.db.QueryRow(ctx, countInviterMonthlyRewardDays, arg.InviterID, arg.RewardInviterAt, arg.RewardInviterAt_2)
	var total_days int32
	err := row.Scan(&total_days)
	return total_days, err
}

const createUserInvite = `-- name: CreateUserInvite :one
INSERT INTO user_invites (id, user_id, inviter_id, entry_count, user_open_id, created_at)
VALUES ($1, $2, $3, 0, $4, now())
RETURNING id, user_id, inviter_id, entry_count, reward_inviter_at, reward_invitee_at, created_at, user_open_id
`

type CreateUserInviteParams struct {
	ID         string      `json:"id"`
	UserID     pgtype.Text `json:"userId"`
	InviterID  pgtype.Text `json:"inviterId"`
	UserOpenID pgtype.Text `json:"userOpenId"`
}

// R-21：冗余被邀请人 openid（注销后行保留，作为被邀请奖励终身一次的判定依据）。
func (q *Queries) CreateUserInvite(ctx context.Context, arg CreateUserInviteParams) (UserInvite, error) {
	row := q.db.QueryRow(ctx, createUserInvite,
		arg.ID,
		arg.UserID,
		arg.InviterID,
		arg.UserOpenID,
	)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InviterID,
		&i.EntryCount,
		&i.RewardInviterAt,
		&i.RewardInviteeAt,
		&i.CreatedAt,
		&i.UserOpenID,
	)
	return i, err
}

const createUserInviteCode = `-- name: CreateUserInviteCode :one
INSERT INTO user_invite_codes (user_id, short_code, created_at)
VALUES ($1, $2, now())
RETURNING user_id, short_code, created_at, expires_at, used_at
`

type CreateUserInviteCodeParams struct {
	UserID    string `json:"userId"`
	ShortCode string `json:"shortCode"`
}

func (q *Queries) CreateUserInviteCode(ctx context.Context, arg CreateUserInviteCodeParams) (UserInviteCode, error) {
	row := q.db.QueryRow(ctx, createUserInviteCode, arg.UserID, arg.ShortCode)
	var i UserInviteCode
	err := row.Scan(
		&i.UserID,
		&i.ShortCode,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UsedAt,
	)
	return i, err
}

const deleteUserInviteCodeByUserID = `-- name: DeleteUserInviteCodeByUserID :exec
DELETE FROM user_invite_codes WHERE user_id = $1
`

func (q *Queries) DeleteUserInviteCodeByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserInviteCodeByUserID, userID)
	return err
}

const getUserInviteByUserID = `-- name: GetUserInviteByUserID :one
SELECT id, user_id, inviter_id, entry_count, reward_inviter_at, reward_invitee_at, created_at, user_open_id FROM user_invites WHERE user_id = $1
`

func (q *Queries) GetUserInviteByUserID(ctx context.Context, userID pgtype.Text) (UserInvite, error) {
	row := q.db.QueryRow(ctx, getUserInviteByUserID, userID)
	var i UserInvite
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.InviterID,
		&i.EntryCount,
		&i.RewardInviterAt,
		&i.RewardInviteeAt,
		&i.CreatedAt,
		&i.UserOpenID,
	)
	return i, err
}

const getUserInviteCode = `-- name: GetUserInviteCode :one
SELECT short_code FROM user_invite_codes WHERE user_id = $1
`

func (q *Queries) GetUserInviteCode(ctx context.Context, userID string) (string, error) {
	row := q.db.QueryRow(ctx, getUserInviteCode, userID)
	var short_code string
	err := row.Scan(&short_code)
	return short_code, err
}

const listUserInvitesByInviter = `-- name: ListUserInvitesByInviter :many
SELECT ui.user_id, u.nickname, u.avatar,
       (u.current_family_id IS NOT NULL
        AND u.current_family_id != u.personal_family_id
        AND u.current_family_id = inv.current_family_id) AS joined
FROM user_invites ui
JOIN users u ON u.id = ui.user_id
JOIN users inv ON inv.id = ui.inviter_id
WHERE ui.inviter_id = $1
ORDER BY ui.created_at DESC
LIMIT 100
`

type ListUserInvitesByInviterRow struct {
	UserID   pgtype.Text `json:"userId"`
	Nickname pgtype.Text `json:"nickname"`
	Avatar   pgtype.Text `json:"avatar"`
	Joined   pgtype.Bool `json:"joined"`
}

func (q *Queries) ListUserInvitesByInviter(ctx context.Context, inviterID pgtype.Text) ([]ListUserInvitesByInviterRow, error) {
	rows, err := q.db.Query(ctx, listUserInvitesByInviter, inviterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserInvitesByInviterRow{}
	for rows.Next() {
		var i ListUserInvitesByInviterRow
		if err := rows.Scan(
			&i.UserID,
			&i.Nickname,
			&i.Avatar,
			&i.Joined,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInviterReward = `-- name: LockInviterReward :exec
SELECT pg_advisory_xact_lock(hashtext('inviter_reward:' || $1))
`

func (q *Queries) LockInviterReward(ctx context.Context, dollar_1 pgtype.Text) error {
	_, err := q.db.Exec(ctx, lockInviterReward, dollar_1)
	return err
}

const markInviteeRewarded = `-- name: MarkInviteeRewarded :execrows
UPDATE user_invites
SET reward_invitee_at = now()
WHERE id = $1 AND reward_invitee_at IS NULL
`

func (q *Queries) MarkInviteeRewarded(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markInviteeRewarded, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markInviterRewarded = `-- name: MarkInviterRewarded :execrows
UPDATE user_invites
SET reward_inviter_at = now()
WHERE id = $1 AND reward_inviter_at IS NULL
`

func (q *Queries) MarkInviterRewarded(ctx context.Context, id string) (int64, error) {
	result, err := q.db.Exec(ctx, markInviterRewarded, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resolveInviterFromCode = `-- name: ResolveInviterFromCode :one
SELECT user_id
FROM user_invite_codes
WHERE short_code = $1
  AND (expires_at IS NULL OR expires_at > now())
`

// 邀请码是邀请人的稳定分享码，可被多个被邀请人多次解析（不限制一次性），
// 过期语义由 user_invite_codes.expires_at（baseline 000001）决定：过期后解析失败。
// R-24：解析为纯读（used_at 死遥测写副作用移除；列保留，将来做过期策略再启用）。
func (q *Queries) ResolveInviterFromCode(ctx context.Context, shortCode string) (string, error) {
	row := q.db.QueryRow(ctx, resolveInviterFromCode, shortCode)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}
