// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AiDailyQuotaUsage struct {
	UserID    string             `json:"userId"`
	QuotaDate pgtype.Date        `json:"quotaDate"`
	Used      int32              `json:"used"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type AiDialogLog struct {
	ID        string             `json:"id"`
	UserID    string             `json:"userId"`
	Role      string             `json:"role"`
	Content   string             `json:"content"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
}

type ApiKey struct {
	ID        string             `json:"id"`
	UserID    string             `json:"userId"`
	KeyHash   string             `json:"keyHash"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	ApiKey    string             `json:"apiKey"`
}

type AutoRecordTrajectory struct {
	ID              string             `json:"id"`
	UserID          string             `json:"userId"`
	Lat             pgtype.Numeric     `json:"lat"`
	Lon             pgtype.Numeric     `json:"lon"`
	RecordedAt      pgtype.Timestamptz `json:"recordedAt"`
	GeocodeAttempts int32              `json:"geocodeAttempts"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

type ClientOpsLog struct {
	ID           string             `json:"id"`
	UserID       string             `json:"userId"`
	Device       string             `json:"device"`
	AppVersion   string             `json:"appVersion"`
	Events       []byte             `json:"events"`
	ClientSentAt pgtype.Timestamptz `json:"clientSentAt"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}

type Diary struct {
	ID         string             `json:"id"`
	UserID     string             `json:"userId"`
	RecordDate pgtype.Date        `json:"recordDate"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
}

type DiaryEntry struct {
	ID            string             `json:"id"`
	DiaryID       string             `json:"diaryId"`
	CreatedBy     string             `json:"createdBy"`
	Text          pgtype.Text        `json:"text"`
	Lat           pgtype.Numeric     `json:"lat"`
	Lon           pgtype.Numeric     `json:"lon"`
	Address       pgtype.Text        `json:"address"`
	DetailAddress pgtype.Text        `json:"detailAddress"`
	RecordTime    pgtype.Timestamptz `json:"recordTime"`
	Sort          int32              `json:"sort"`
	Color         pgtype.Text        `json:"color"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type DiaryEntryImage struct {
	ID           string             `json:"id"`
	DiaryEntryID string             `json:"diaryEntryId"`
	FileID       string             `json:"fileId"`
	SortOrder    int32              `json:"sortOrder"`
	CreatedAt    pgtype.Timestamptz `json:"createdAt"`
}

type Family struct {
	ID         string             `json:"id"`
	IsPersonal bool               `json:"isPersonal"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type FamilyDailyCover struct {
	FamilyID          string             `json:"familyId"`
	RecordDate        pgtype.Date        `json:"recordDate"`
	CoverFileID       pgtype.Text        `json:"coverFileId"`
	CoverType         string             `json:"coverType"`
	UpdatedAt         pgtype.Timestamptz `json:"updatedAt"`
	ManualCoverFileID pgtype.Text        `json:"manualCoverFileId"`
}

type FamilyMember struct {
	ID       string             `json:"id"`
	FamilyID string             `json:"familyId"`
	UserID   string             `json:"userId"`
	Role     string             `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joinedAt"`
}

type File struct {
	ID          string             `json:"id"`
	CreatedBy   pgtype.Text        `json:"createdBy"`
	Path        string             `json:"path"`
	Name        string             `json:"name"`
	Suffix      string             `json:"suffix"`
	SizeBytes   int64              `json:"sizeBytes"`
	FileType    string             `json:"fileType"`
	Metadata    []byte             `json:"metadata"`
	CreatedAt   pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	StorageType string             `json:"storageType"`
}

type Memory struct {
	ID         string             `json:"id"`
	UserID     string             `json:"userId"`
	RecordTime pgtype.Timestamptz `json:"recordTime"`
	RecordDate pgtype.Date        `json:"recordDate"`
	Title      string             `json:"title"`
	Content    string             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type Order struct {
	ID            string             `json:"id"`
	UserID        pgtype.Text        `json:"userId"`
	VipID         string             `json:"vipId"`
	OutTradeNo    string             `json:"outTradeNo"`
	Channel       string             `json:"channel"`
	State         string             `json:"state"`
	Amount        int32              `json:"amount"`
	PrepayID      pgtype.Text        `json:"prepayId"`
	TransactionID pgtype.Text        `json:"transactionId"`
	PaidAt        pgtype.Timestamptz `json:"paidAt"`
	CreatedAt     pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt     pgtype.Timestamptz `json:"updatedAt"`
}

type User struct {
	ID                        string             `json:"id"`
	OpenID                    string             `json:"openId"`
	Unionid                   pgtype.Text        `json:"unionid"`
	PhoneNumber               pgtype.Text        `json:"phoneNumber"`
	Avatar                    pgtype.Text        `json:"avatar"`
	AvatarFileID              pgtype.Text        `json:"avatarFileId"`
	Nickname                  pgtype.Text        `json:"nickname"`
	UserType                  string             `json:"userType"`
	PhoneBindTime             pgtype.Timestamptz `json:"phoneBindTime"`
	AutoRecordEnabled         bool               `json:"autoRecordEnabled"`
	PersonalFamilyID          pgtype.Text        `json:"personalFamilyId"`
	CurrentFamilyID           pgtype.Text        `json:"currentFamilyId"`
	CreatedAt                 pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt                 pgtype.Timestamptz `json:"updatedAt"`
	SessionKey                pgtype.Text        `json:"sessionKey"`
	InvitedBy                 pgtype.Text        `json:"invitedBy"`
	AbnormalSubscribeAccepted bool               `json:"abnormalSubscribeAccepted"`
	AbnormalAlertSentAt       pgtype.Timestamptz `json:"abnormalAlertSentAt"`
	LastActiveAt              pgtype.Timestamptz `json:"lastActiveAt"`
	Lang                      string             `json:"lang"`
	ImageStorageBytes         int64              `json:"imageStorageBytes"`
}

type UserAvatarMarker struct {
	UserID      string             `json:"userId"`
	MarkerPath  string             `json:"markerPath"`
	UpdatedAt   pgtype.Timestamptz `json:"updatedAt"`
	StorageType string             `json:"storageType"`
}

type UserCommonAddress struct {
	UserID    string             `json:"userId"`
	Name      string             `json:"name"`
	Lat       pgtype.Numeric     `json:"lat"`
	Lon       pgtype.Numeric     `json:"lon"`
	Count     int32              `json:"count"`
	UpdatedAt pgtype.Timestamptz `json:"updatedAt"`
}

type UserInvite struct {
	ID              string             `json:"id"`
	UserID          pgtype.Text        `json:"userId"`
	InviterID       pgtype.Text        `json:"inviterId"`
	EntryCount      int32              `json:"entryCount"`
	RewardInviterAt pgtype.Timestamptz `json:"rewardInviterAt"`
	RewardInviteeAt pgtype.Timestamptz `json:"rewardInviteeAt"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UserOpenID      pgtype.Text        `json:"userOpenId"`
}

type UserInviteCode struct {
	UserID    string             `json:"userId"`
	ShortCode string             `json:"shortCode"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	ExpiresAt pgtype.Timestamptz `json:"expiresAt"`
	UsedAt    pgtype.Timestamptz `json:"usedAt"`
}

type UserVip struct {
	ID         string             `json:"id"`
	UserID     string             `json:"userId"`
	BeginTime  pgtype.Timestamptz `json:"beginTime"`
	ExpireTime pgtype.Timestamptz `json:"expireTime"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type UserVipClaim struct {
	ID        string             `json:"id"`
	UserID    pgtype.Text        `json:"userId"`
	VipID     string             `json:"vipId"`
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	OpenID    pgtype.Text        `json:"openId"`
}

type Vip struct {
	ID              string             `json:"id"`
	Type            string             `json:"type"`
	Name            string             `json:"name"`
	TimeLimitMark   string             `json:"timeLimitMark"`
	TimeLimitNumber int32              `json:"timeLimitNumber"`
	ProductID       pgtype.Text        `json:"productId"`
	Sort            int32              `json:"sort"`
	IsActive        bool               `json:"isActive"`
	Prices          []byte             `json:"prices"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
}

type WxMpAccount struct {
	ID               string             `json:"id"`
	UserID           pgtype.Text        `json:"userId"`
	MpOpenid         string             `json:"mpOpenid"`
	Unionid          pgtype.Text        `json:"unionid"`
	Nickname         pgtype.Text        `json:"nickname"`
	Avatar           pgtype.Text        `json:"avatar"`
	Subscribed       bool               `json:"subscribed"`
	SubscribeTime    pgtype.Timestamptz `json:"subscribeTime"`
	LastInteractTime pgtype.Timestamptz `json:"lastInteractTime"`
	CreatedAt        pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt        pgtype.Timestamptz `json:"updatedAt"`
}
