// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: order.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeOrder = `-- name: CloseOrder :execrows
UPDATE orders SET state = 'closed', updated_at = now() WHERE out_trade_no = $1 AND state = 'pending' AND user_id = $2
`

type CloseOrderParams struct {
	OutTradeNo string      `json:"outTradeNo"`
	UserID     pgtype.Text `json:"userId"`
}

func (q *Queries) CloseOrder(ctx context.Context, arg CloseOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeOrder, arg.OutTradeNo, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeOrdersBatch = `-- name: CloseOrdersBatch :execrows
UPDATE orders AS o
SET state = 'closed', updated_at = now()
FROM unnest($2::text[]) WITH ORDINALITY AS t(no, ord)
WHERE o.out_trade_no = t.no
  AND o.user_id = ($1::text[])[t.ord]
  AND o.state = 'pending'
`

type CloseOrdersBatchParams struct {
	UserIds     []string `json:"userIds"`
	OutTradeNos []string `json:"outTradeNos"`
}

// 两个数组按位置配对（B2-10）：out_trade_nos 展开为 (订单号, 序号)，
// user_ids 按下标取同位置的 user_id，避免双 ANY 独立展开产生笛卡尔误关他人订单。
func (q *Queries) CloseOrdersBatch(ctx context.Context, arg CloseOrdersBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, closeOrdersBatch, arg.UserIds, arg.OutTradeNos)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closeOwnerlessPendingOrders = `-- name: CloseOwnerlessPendingOrders :execrows
UPDATE orders SET state = 'closed', updated_at = now()
WHERE orders.id IN (
    SELECT o.id FROM orders o
    WHERE o.state = 'pending' AND o.user_id IS NULL AND o.created_at < $1
    ORDER BY o.id ASC
    LIMIT 1000
)
`

// R-17：关闭无主（user_id IS NULL，用户注销产生）的过期 pending 订单，避免永久滞留。
func (q *Queries) CloseOwnerlessPendingOrders(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, closeOwnerlessPendingOrders, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const closePendingOrdersByUser = `-- name: ClosePendingOrdersByUser :exec
UPDATE orders SET state = 'closed', updated_at = now()
WHERE user_id = $1 AND state = 'pending' AND created_at < now() - interval '5 minutes'
`

func (q *Queries) ClosePendingOrdersByUser(ctx context.Context, userID pgtype.Text) error {
	_, err := q.db.Exec(ctx, closePendingOrdersByUser, userID)
	return err
}

const closePendingOrdersByUserAndVIP = `-- name: ClosePendingOrdersByUserAndVIP :exec
UPDATE orders SET state = 'closed', updated_at = now()
WHERE user_id = $1 AND vip_id = $2 AND state = 'pending' AND created_at < now() - interval '5 minutes'
`

type ClosePendingOrdersByUserAndVIPParams struct {
	UserID pgtype.Text `json:"userId"`
	VipID  string      `json:"vipId"`
}

func (q *Queries) ClosePendingOrdersByUserAndVIP(ctx context.Context, arg ClosePendingOrdersByUserAndVIPParams) error {
	_, err := q.db.Exec(ctx, closePendingOrdersByUserAndVIP, arg.UserID, arg.VipID)
	return err
}

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (id, user_id, vip_id, out_trade_no, channel, state, amount, prepay_id, created_at, updated_at)
VALUES ($1, $2, $3, $4, 'virtual_pay', 'pending', $5, $6, now(), now())
RETURNING id, user_id, vip_id, out_trade_no, channel, state, amount, prepay_id, transaction_id, paid_at, created_at, updated_at
`

type CreateOrderParams struct {
	ID         string      `json:"id"`
	UserID     pgtype.Text `json:"userId"`
	VipID      string      `json:"vipId"`
	OutTradeNo string      `json:"outTradeNo"`
	Amount     int32       `json:"amount"`
	PrepayID   pgtype.Text `json:"prepayId"`
}

func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ID,
		arg.UserID,
		arg.VipID,
		arg.OutTradeNo,
		arg.Amount,
		arg.PrepayID,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VipID,
		&i.OutTradeNo,
		&i.Channel,
		&i.State,
		&i.Amount,
		&i.PrepayID,
		&i.TransactionID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOrderByOutTradeNo = `-- name: GetOrderByOutTradeNo :one
SELECT id, user_id, vip_id, out_trade_no, channel, state, amount, prepay_id, transaction_id, paid_at, created_at, updated_at FROM orders WHERE out_trade_no = $1
`

func (q *Queries) GetOrderByOutTradeNo(ctx context.Context, outTradeNo string) (Order, error) {
	row := q.db.QueryRow(ctx, getOrderByOutTradeNo, outTradeNo)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VipID,
		&i.OutTradeNo,
		&i.Channel,
		&i.State,
		&i.Amount,
		&i.PrepayID,
		&i.TransactionID,
		&i.PaidAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listPendingOrdersBefore = `-- name: ListPendingOrdersBefore :many
SELECT id, user_id, vip_id, out_trade_no, channel, state, amount, prepay_id, transaction_id, paid_at, created_at, updated_at FROM orders
WHERE state = 'pending'
  AND created_at < $1
  AND user_id IS NOT NULL
  AND id > $2
ORDER BY id ASC
LIMIT 1000
`

type ListPendingOrdersBeforeParams struct {
	CreatedAt pgtype.Timestamptz `json:"createdAt"`
	CursorID  string             `json:"cursorId"`
}

func (q *Queries) ListPendingOrdersBefore(ctx context.Context, arg ListPendingOrdersBeforeParams) ([]Order, error) {
	rows, err := q.db.Query(ctx, listPendingOrdersBefore, arg.CreatedAt, arg.CursorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Order{}
	for rows.Next() {
		var i Order
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VipID,
			&i.OutTradeNo,
			&i.Channel,
			&i.State,
			&i.Amount,
			&i.PrepayID,
			&i.TransactionID,
			&i.PaidAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markClosedOrderPaid = `-- name: MarkClosedOrderPaid :execrows
UPDATE orders SET
    state = 'paid',
    transaction_id = $2,
    paid_at = now(),
    updated_at = now()
WHERE out_trade_no = $1 AND state = 'closed'
`

type MarkClosedOrderPaidParams struct {
	OutTradeNo    string      `json:"outTradeNo"`
	TransactionID pgtype.Text `json:"transactionId"`
}

// VP-P1-02：订单已被本地关闭（取消/超时/换单清理）但用户仍完成支付，补记为 paid 以便发货。
func (q *Queries) MarkClosedOrderPaid(ctx context.Context, arg MarkClosedOrderPaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, markClosedOrderPaid, arg.OutTradeNo, arg.TransactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const nullifyOrdersByUser = `-- name: NullifyOrdersByUser :exec
UPDATE orders SET user_id = NULL, updated_at = now() WHERE user_id = $1
`

func (q *Queries) NullifyOrdersByUser(ctx context.Context, userID pgtype.Text) error {
	_, err := q.db.Exec(ctx, nullifyOrdersByUser, userID)
	return err
}

const updateOrderPaid = `-- name: UpdateOrderPaid :execrows
UPDATE orders SET
    state = 'paid',
    transaction_id = $2,
    paid_at = now(),
    updated_at = now()
WHERE out_trade_no = $1 AND state = 'pending'
`

type UpdateOrderPaidParams struct {
	OutTradeNo    string      `json:"outTradeNo"`
	TransactionID pgtype.Text `json:"transactionId"`
}

func (q *Queries) UpdateOrderPaid(ctx context.Context, arg UpdateOrderPaidParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateOrderPaid, arg.OutTradeNo, arg.TransactionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
