// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	BatchCreateDiaryEntryImages(ctx context.Context, arg BatchCreateDiaryEntryImagesParams) error
	BatchDeleteFiles(ctx context.Context, dollar_1 []string) ([]BatchDeleteFilesRow, error)
	BatchMigrateUsersDailyCoversToPersonal(ctx context.Context, arg BatchMigrateUsersDailyCoversToPersonalParams) error
	BatchUpdateUsersCurrentFamilyToPersonal(ctx context.Context, arg BatchUpdateUsersCurrentFamilyToPersonalParams) error
	BatchUpsertFamilyMembership(ctx context.Context, arg BatchUpsertFamilyMembershipParams) error
	BatchUpsertFamilyMembershipOwner(ctx context.Context, arg BatchUpsertFamilyMembershipOwnerParams) error
	// A-FIX-03：绑定手机号的原子日限——仅当 phone_bind_time 为空或不在今天（上海时区）时写入，
	// 避免「检查-再更新」竞态下并发绑定绕过日限、反复消耗微信认证额度。
	BindUserPhoneIfAllowed(ctx context.Context, arg BindUserPhoneIfAllowedParams) (int64, error)
	// 并发首次激活竞态防护：GetUserVIPForUpdate 对不存在的行无法加锁，两个并发首次激活
	// 都走 ErrNoRows 创建路径会各自按 now 计算 expire、GREATEST 只保留较大者导致较小档时长丢失。
	// 先 ON CONFLICT DO NOTHING 占位（expire=now+1s，满足 CHECK (expire_time > begin_time)），
	// 再 FOR UPDATE 重读串行化首次创建。
	ClaimUserVIPRow(ctx context.Context, arg ClaimUserVIPRowParams) error
	ClearAvatarReferencesToOrphanFiles(ctx context.Context) error
	ClearFamilyDailyImageCoverByFileID(ctx context.Context, arg ClearFamilyDailyImageCoverByFileIDParams) error
	ClearFamilyDailyImageCoverByFileIDs(ctx context.Context, arg ClearFamilyDailyImageCoverByFileIDsParams) error
	ClearFamilyDailyManualCover(ctx context.Context, arg ClearFamilyDailyManualCoverParams) error
	ClearFamilyDailyManualCoverByFileID(ctx context.Context, arg ClearFamilyDailyManualCoverByFileIDParams) error
	ClearFamilyDailyManualCoverByFileIDs(ctx context.Context, arg ClearFamilyDailyManualCoverByFileIDsParams) error
	ClearTrajectoryFamilyID(ctx context.Context, familyID string) error
	ClearUserAvatarByFile(ctx context.Context, arg ClearUserAvatarByFileParams) error
	CloseOrder(ctx context.Context, arg CloseOrderParams) (int64, error)
	// 两个数组按位置配对：out_trade_nos 展开为 (订单号, 序号)，
	// user_ids 按下标取同位置的 user_id，避免双 ANY 独立展开产生笛卡尔误关他人订单。
	CloseOrdersBatch(ctx context.Context, arg CloseOrdersBatchParams) (int64, error)
	// 关闭无主（user_id IS NULL，用户注销产生）的过期 pending 订单，避免永久滞留。
	CloseOwnerlessPendingOrders(ctx context.Context, createdAt pgtype.Timestamptz) (int64, error)
	ClosePendingOrdersByUser(ctx context.Context, userID pgtype.Text) error
	ClosePendingOrdersByUserAndVIP(ctx context.Context, arg ClosePendingOrdersByUserAndVIPParams) error
	// 候选积压量（满批时才统计），超过阈值输出 auto_record_backlog_warn。
	CountAutoRecordCandidates(ctx context.Context, maxGeocodeAttempts int32) (int64, error)
	CountDiaryEntries(ctx context.Context, arg CountDiaryEntriesParams) (int64, error)
	CountDiaryEntriesByUsers(ctx context.Context, dollar_1 []string) (int64, error)
	CountFamilyDailyCovers(ctx context.Context, familyID string) (int64, error)
	CountFamilyMembers(ctx context.Context, familyID string) (int64, error)
	CountInviterMonthlyRewardDays(ctx context.Context, arg CountInviterMonthlyRewardDaysParams) (int32, error)
	CountWeeklyDiaryEntriesByUsers(ctx context.Context, arg CountWeeklyDiaryEntriesByUsersParams) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateAutoRecordEntry(ctx context.Context, arg CreateAutoRecordEntryParams) error
	CreateDiaryEntry(ctx context.Context, arg CreateDiaryEntryParams) (DiaryEntry, error)
	CreateDiaryEntryImage(ctx context.Context, arg CreateDiaryEntryImageParams) error
	CreateFamily(ctx context.Context, arg CreateFamilyParams) (string, error)
	CreateFile(ctx context.Context, arg CreateFileParams) (File, error)
	CreateMemory(ctx context.Context, arg CreateMemoryParams) (Memory, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// 冗余被邀请人 openid（注销后行保留，作为被邀请奖励终身一次的判定依据）。
	CreateUserInvite(ctx context.Context, arg CreateUserInviteParams) (UserInvite, error)
	CreateUserInviteCode(ctx context.Context, arg CreateUserInviteCodeParams) (UserInviteCode, error)
	DecrementAIDailyQuotaUsed(ctx context.Context, arg DecrementAIDailyQuotaUsedParams) (int32, error)
	// GREATEST 保底：并发/重复扣减时计量不得为负（负值会绕过存储限额检查）。
	DecrementUserImageStorage(ctx context.Context, arg DecrementUserImageStorageParams) error
	DeleteAIDailyQuotaUsageByUserID(ctx context.Context, userID string) error
	DeleteAPIKeyByUser(ctx context.Context, userID string) error
	DeleteDiaryEntriesByDiaryID(ctx context.Context, diaryID string) (int64, error)
	DeleteDiaryEntryByID(ctx context.Context, id string) error
	DeleteDiaryEntryImages(ctx context.Context, diaryEntryID string) error
	// 先删图片关联并返回 file_id，再由调用方在同一事务内删除条目。
	// 拆成两条语句，避免数据修改 CTE 顺序不可预测导致 file_id 漏返回。
	DeleteDiaryEntryImagesReturningFileIDs(ctx context.Context, diaryEntryID string) ([]string, error)
	// 条件删除：头行 FOR UPDATE（LockDiaryByIDForUpdate）与本语句配合，
	// 与并发新增条目（FK KEY SHARE）串行化，关闭「计数后删行」窗口内
	// 并发已提交条目被级联删除的丢失路径（docs/OBJECTIVES A1）。
	DeleteDiaryIfEmpty(ctx context.Context, id string) (int64, error)
	// 先删图片关联并返回 file_id，再由调用方在同一事务内删除日记（级联删除条目）。
	// 拆成两条语句：PostgreSQL 不保证同一 WITH 内多个数据修改 CTE 的执行顺序，
	// 若级联（删日记）先于显式 DELETE...RETURNING 执行，file_id 会为空导致文件漏清理。
	DeleteDiaryImagesReturningFileIDs(ctx context.Context, diaryID string) ([]string, error)
	DeleteFamily(ctx context.Context, id string) error
	DeleteFamilyDailyCovers(ctx context.Context, familyID string) error
	DeleteFamilyMembers(ctx context.Context, familyID string) error
	DeleteFamilyMembership(ctx context.Context, arg DeleteFamilyMembershipParams) error
	DeleteFile(ctx context.Context, id string) error
	DeleteMemoriesByUserAndDate(ctx context.Context, arg DeleteMemoriesByUserAndDateParams) (int64, error)
	DeleteMemory(ctx context.Context, arg DeleteMemoryParams) (int64, error)
	DeleteOldClientOpsLogs(ctx context.Context, dollar_1 int64) (int64, error)
	DeleteOldDialogLogs(ctx context.Context, dollar_1 int64) (int64, error)
	DeleteStaleTrajectories(ctx context.Context, dollar_1 int64) (int64, error)
	DeleteTrajectories(ctx context.Context, dollar_1 []string) error
	DeleteTrajectoryCovers(ctx context.Context, arg DeleteTrajectoryCoversParams) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserCommonAddressByName(ctx context.Context, arg DeleteUserCommonAddressByNameParams) error
	DeleteUserCommonAddresses(ctx context.Context, userID string) error
	DeleteUserInviteCodeByUserID(ctx context.Context, userID string) error
	DeleteUserVIP(ctx context.Context, userID string) error
	// openid 曾领过被邀请奖励（墓碑行，注销后保留，见迁移 000008/000011）则本次邀请
	// 关系整体不发奖：本人 +3 与邀请人 +7 均不发，邀请行照常创建且对邀请人可见，
	// 注册/绑定/加入主流程照常成功。
	ExistsInviteeRewardByOpenID(ctx context.Context, userOpenID pgtype.Text) (bool, error)
	FindTrajectoryCovers(ctx context.Context, arg FindTrajectoryCoversParams) ([]FindTrajectoryCoversRow, error)
	GetAIDailyQuotaUsed(ctx context.Context, arg GetAIDailyQuotaUsedParams) (int32, error)
	GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error)
	GetAPIKeyByUser(ctx context.Context, userID string) (GetAPIKeyByUserRow, error)
	// trial 下线闸门：仅返回在售商品，0 行=已下线（注册路径静默跳过、端点 404）。
	// 支付发货沿用 GetVIPByID（不过滤 is_active），已支付订单不因商品下线而漏发。
	GetActiveVIPByID(ctx context.Context, id string) (Vip, error)
	GetDiaryByID(ctx context.Context, id string) (Diary, error)
	GetDiaryByUserAndDate(ctx context.Context, arg GetDiaryByUserAndDateParams) (Diary, error)
	GetDiaryEntriesByImageID(ctx context.Context, arg GetDiaryEntriesByImageIDParams) ([]int32, error)
	GetDiaryEntry(ctx context.Context, id string) (DiaryEntry, error)
	GetDiaryFirstRecordDate(ctx context.Context, dollar_1 []string) (pgtype.Date, error)
	GetFamilyByID(ctx context.Context, id string) (GetFamilyByIDRow, error)
	GetFamilyDailyCover(ctx context.Context, arg GetFamilyDailyCoverParams) (GetFamilyDailyCoverRow, error)
	GetFamilyOwner(ctx context.Context, familyID string) (string, error)
	GetFamilyRemovedMembers(ctx context.Context, id string) ([]byte, error)
	GetFileByID(ctx context.Context, id string) (File, error)
	GetFileByIDForUpdate(ctx context.Context, id string) (File, error)
	GetFileByPath(ctx context.Context, path string) (File, error)
	GetFileReferences(ctx context.Context, coverFileID pgtype.Text) (GetFileReferencesRow, error)
	GetFilesByIDs(ctx context.Context, dollar_1 []string) ([]File, error)
	GetLatestCoordinateByAddress(ctx context.Context, arg GetLatestCoordinateByAddressParams) (GetLatestCoordinateByAddressRow, error)
	// 选择当日最新图片日记作为 image 优先级封面。
	// 排序语义：用户手动排序（sort_order 越小越靠前） > 日记记录时间 > 图片上传时间。
	GetLatestImageEntry(ctx context.Context, arg GetLatestImageEntryParams) (GetLatestImageEntryRow, error)
	GetMemory(ctx context.Context, arg GetMemoryParams) (Memory, error)
	GetOrderByOutTradeNo(ctx context.Context, outTradeNo string) (Order, error)
	GetUserAvatarMarker(ctx context.Context, userID string) (GetUserAvatarMarkerRow, error)
	GetUserAvatarMarkersByIDs(ctx context.Context, dollar_1 []string) ([]GetUserAvatarMarkersByIDsRow, error)
	GetUserByID(ctx context.Context, id string) (GetUserByIDRow, error)
	GetUserByIDForUpdate(ctx context.Context, id string) (GetUserByIDForUpdateRow, error)
	GetUserByOpenID(ctx context.Context, openID string) (GetUserByOpenIDRow, error)
	GetUserByUnionID(ctx context.Context, unionid pgtype.Text) (GetUserByUnionIDRow, error)
	GetUserCommonAddress(ctx context.Context, arg GetUserCommonAddressParams) (GetUserCommonAddressRow, error)
	GetUserCommonAddressForUpdate(ctx context.Context, arg GetUserCommonAddressForUpdateParams) (GetUserCommonAddressForUpdateRow, error)
	GetUserImageStorageUsage(ctx context.Context, id string) (int64, error)
	GetUserInviteByUserID(ctx context.Context, userID pgtype.Text) (UserInvite, error)
	GetUserInviteCode(ctx context.Context, userID string) (string, error)
	GetUserSessionKeyByID(ctx context.Context, id string) (pgtype.Text, error)
	GetUserVIP(ctx context.Context, userID string) (UserVip, error)
	GetUserVIPForUpdate(ctx context.Context, userID string) (UserVip, error)
	GetVIPByID(ctx context.Context, id string) (Vip, error)
	GetWxMPAccountByOpenID(ctx context.Context, mpOpenid string) (WxMpAccount, error)
	GetWxMPAccountByUnionID(ctx context.Context, unionid pgtype.Text) (WxMpAccount, error)
	GetWxMPAccountByUserID(ctx context.Context, userID pgtype.Text) (WxMpAccount, error)
	HasVIPClaim(ctx context.Context, arg HasVIPClaimParams) (bool, error)
	// 按微信主体判重（注销重注册后仍能识别已领取），openid 为空时调用方回退 HasVIPClaim。
	HasVIPClaimByOpenID(ctx context.Context, arg HasVIPClaimByOpenIDParams) (bool, error)
	IncrementAIDailyQuotaUsed(ctx context.Context, arg IncrementAIDailyQuotaUsedParams) (IncrementAIDailyQuotaUsedRow, error)
	IncrementTrajectoryGeocodeAttempts(ctx context.Context, dollar_1 []string) error
	// 条件原子扣减——超限时更新 0 行，由调用方识别拒绝，杜绝 check-then-act 竞态。
	IncrementUserImageStorage(ctx context.Context, arg IncrementUserImageStorageParams) (int64, error)
	InsertAIDialogLog(ctx context.Context, arg InsertAIDialogLogParams) error
	InsertClientOpsLog(ctx context.Context, arg InsertClientOpsLogParams) (string, error)
	// 重复上报（同一 user+recorded_at+lat+lon）静默忽略，避免重试产生重复轨迹。
	InsertTrajectories(ctx context.Context, arg InsertTrajectoriesParams) error
	InsertUserCommonAddresses(ctx context.Context, arg InsertUserCommonAddressesParams) error
	IsFamilyMember(ctx context.Context, arg IsFamilyMemberParams) (bool, error)
	IsImageUsedByFamilyDate(ctx context.Context, arg IsImageUsedByFamilyDateParams) (bool, error)
	LinkWxMPAccountByUnionID(ctx context.Context, arg LinkWxMPAccountByUnionIDParams) error
	ListAIBackgroundEntries(ctx context.Context, arg ListAIBackgroundEntriesParams) ([]ListAIBackgroundEntriesRow, error)
	ListAbnormalAlertCandidates(ctx context.Context, arg ListAbnormalAlertCandidatesParams) ([]ListAbnormalAlertCandidatesRow, error)
	ListActiveFreeVIPs(ctx context.Context) ([]Vip, error)
	ListActivePaidVIPs(ctx context.Context) ([]Vip, error)
	ListAddressEntriesByDates(ctx context.Context, arg ListAddressEntriesByDatesParams) ([]ListAddressEntriesByDatesRow, error)
	// 同日去重集合化：取当天全部自动条目的 id+地址，后台与手动即时成文共用；
	// 后者需要已存在条目 id 供响应契约（ORDER BY DESC 保证首条命中即最新）。
	ListAutoEntryAddressesByDate(ctx context.Context, arg ListAutoEntryAddressesByDateParams) ([]ListAutoEntryAddressesByDateRow, error)
	// 公平轮转——按 user_id keyset 分页，避免「按积压量 ORDER BY cnt DESC」令低频用户饥饿；
	// 仅取仍有未达重试上限轨迹的用户。
	ListAutoRecordCandidates(ctx context.Context, arg ListAutoRecordCandidatesParams) ([]string, error)
	ListDiaryCards(ctx context.Context, arg ListDiaryCardsParams) ([]ListDiaryCardsRow, error)
	ListDiaryCardsByDates(ctx context.Context, arg ListDiaryCardsByDatesParams) ([]ListDiaryCardsByDatesRow, error)
	ListDiaryEntries(ctx context.Context, arg ListDiaryEntriesParams) ([]ListDiaryEntriesRow, error)
	// 排序与展示列同源：record_time 被编辑后结果顺序仍与展示值一致。
	ListDiaryEntriesByDateRange(ctx context.Context, arg ListDiaryEntriesByDateRangeParams) ([]ListDiaryEntriesByDateRangeRow, error)
	ListDiaryEntryImageFileIDsByDiaryID(ctx context.Context, diaryID string) ([]string, error)
	ListDiaryEntryImagePaths(ctx context.Context, diaryEntryID string) ([]ListDiaryEntryImagePathsRow, error)
	ListDiaryEntryImagePathsByEntryIDs(ctx context.Context, dollar_1 []string) ([]ListDiaryEntryImagePathsByEntryIDsRow, error)
	ListDiaryEntryImages(ctx context.Context, diaryEntryID string) ([]string, error)
	ListFamilyDailyCovers(ctx context.Context, arg ListFamilyDailyCoversParams) ([]ListFamilyDailyCoversRow, error)
	ListFamilyMemberPersonalFamilies(ctx context.Context, familyID string) ([]ListFamilyMemberPersonalFamiliesRow, error)
	ListFamilyMembers(ctx context.Context, familyID string) ([]ListFamilyMembersRow, error)
	// 一次往返同时取用户当前家庭与其成员列表（替代 GetUserByID + ListFamilyMembers 两段串行，
	// 是 diary 全部端点的公共前缀）。LEFT JOIN 保形：无家庭时返回单行全 NULL（fm.* 判空跳过），
	// 用户不存在时 0 行（调用方转 ErrNoRows），与旧两查语义逐一对齐。
	ListFamilyMembersByUserID(ctx context.Context, id string) ([]ListFamilyMembersByUserIDRow, error)
	ListFilesByCreator(ctx context.Context, arg ListFilesByCreatorParams) ([]ListFilesByCreatorRow, error)
	// 按地址批量取最新坐标（DISTINCT ON），避免循环内逐条 N+1 查询。
	ListLatestCoordinatesByAddresses(ctx context.Context, arg ListLatestCoordinatesByAddressesParams) ([]ListLatestCoordinatesByAddressesRow, error)
	ListLocationEntries(ctx context.Context, arg ListLocationEntriesParams) ([]ListLocationEntriesRow, error)
	ListMemoriesByDateRange(ctx context.Context, arg ListMemoriesByDateRangeParams) ([]ListMemoriesByDateRangeRow, error)
	ListMemoriesByUserAndDate(ctx context.Context, arg ListMemoriesByUserAndDateParams) ([]ListMemoriesByUserAndDateRow, error)
	ListOrphanFilesByCreator(ctx context.Context, arg ListOrphanFilesByCreatorParams) ([]ListOrphanFilesByCreatorRow, error)
	ListPendingOrdersBefore(ctx context.Context, arg ListPendingOrdersBeforeParams) ([]Order, error)
	ListRecentDialogLogs(ctx context.Context, arg ListRecentDialogLogsParams) ([]AiDialogLog, error)
	ListTopAddressesByUser(ctx context.Context, arg ListTopAddressesByUserParams) ([]ListTopAddressesByUserRow, error)
	// 排除达到逆地理重试上限的终态轨迹，避免其每轮重复聚类/告警（保留至 7 天清理）。
	ListTrajectoriesByUser(ctx context.Context, arg ListTrajectoriesByUserParams) ([]AutoRecordTrajectory, error)
	ListUserCommonAddresses(ctx context.Context, userID string) ([]ListUserCommonAddressesRow, error)
	ListUserInviteQRCodeFiles(ctx context.Context, arg ListUserInviteQRCodeFilesParams) ([]ListUserInviteQRCodeFilesRow, error)
	// LEFT JOIN：受邀人注销后行保留（user_id 置 NULL，000011），关系记录仍应在
	// 邀请人"我的邀请"列表可见；昵称/头像为 NULL，由 handler 映射为"已注销"占位。
	ListUserInvitesByInviter(ctx context.Context, inviterID pgtype.Text) ([]ListUserInvitesByInviterRow, error)
	ListUserMcpEntries(ctx context.Context, arg ListUserMcpEntriesParams) ([]ListUserMcpEntriesRow, error)
	// keyset 游标分页：按 created_by 排序 + 游标 + LIMIT，避免一次性物化全部变更用户。
	ListUsersWithDiaryChangesSince(ctx context.Context, arg ListUsersWithDiaryChangesSinceParams) ([]string, error)
	LockDiaryByIDForUpdate(ctx context.Context, id string) (string, error)
	LockInviterReward(ctx context.Context, dollar_1 pgtype.Text) error
	MarkAbnormalAlertSent(ctx context.Context, id string) (int64, error)
	// VP-P1-02：订单已被本地关闭（取消/超时/换单清理）但用户仍完成支付，补记为 paid 以便发货。
	MarkClosedOrderPaid(ctx context.Context, arg MarkClosedOrderPaidParams) (int64, error)
	MarkInviteeRewarded(ctx context.Context, id string) (int64, error)
	MarkInviterRewarded(ctx context.Context, id string) (int64, error)
	// upsert 目标行（源行坐标/计数随 INSERT 带入），目标行不存在时计数不静默丢失；
	// ON CONFLICT 保证并发合并计数不丢。源行删除由 DeleteUserCommonAddressByName 在调用方事务内完成
	// （H2：sqlc 会静默丢弃同一 named 块中的第二条语句，不可合并写在这里）。
	MergeUserCommonAddress(ctx context.Context, arg MergeUserCommonAddressParams) error
	MigrateFamilyDailyCovers(ctx context.Context, arg MigrateFamilyDailyCoversParams) error
	MigrateUserDailyCoversToFamily(ctx context.Context, arg MigrateUserDailyCoversToFamilyParams) error
	NeedsCommonAddressRefresh(ctx context.Context, userID string) (pgtype.Bool, error)
	NullifyOrdersByUser(ctx context.Context, userID pgtype.Text) error
	RecordRemovedMember(ctx context.Context, arg RecordRemovedMemberParams) error
	RenameUserCommonAddress(ctx context.Context, arg RenameUserCommonAddressParams) error
	// 邀请码是邀请人的稳定分享码，可被多个被邀请人多次解析（不限制一次性），
	// 过期语义由 user_invite_codes.expires_at（baseline 000001）决定：过期后解析失败。
	// 解析为纯读（used_at 死遥测写副作用移除；列保留，将来做过期策略再启用）。
	ResolveInviterFromCode(ctx context.Context, shortCode string) (string, error)
	// 邀请二维码/分享海报豁免：invite/qrcode.go generate 写入的海报记录 metadata 恒含 'raw' 键
	//（轨迹图为 {family_id, record_date}、头像 marker 为 {}，均无该键，故 'raw' 是 invite 资产唯一识别特征）。
	// 已分发到微信会话的图片 URL 不能被 7 天窗口静默回收成 404；其回收由两条替代路径覆盖：
	// ①重生成替换（generate 事务内删旧记录、提交后删旧物理文件）②注销清理（DeleteAccount 按
	// created_by 收集全部 files 路径删物理文件）。COALESCE 兜底 metadata 为 NULL 的行维持可回收。
	ScanOldSystemFiles(ctx context.Context, id string) ([]ScanOldSystemFilesRow, error)
	// 宽限窗 7 天：上传成功但尚未挂到任何引用（客户端崩溃/离线草稿）的图片不应被回收，
	// 与代码注释及 spec「7 天孤儿清理兜底」口径一致。
	ScanOrphanFiles(ctx context.Context, id string) ([]ScanOrphanFilesRow, error)
	SetFamilyDailyManualCover(ctx context.Context, arg SetFamilyDailyManualCoverParams) error
	TouchDiaryUpdatedAt(ctx context.Context, id string) error
	TouchWxMPAccountInteractTime(ctx context.Context, mpOpenid string) error
	UpdateDiaryEntriesAddress(ctx context.Context, arg UpdateDiaryEntriesAddressParams) (int64, error)
	UpdateDiaryEntriesAddressBatch(ctx context.Context, arg UpdateDiaryEntriesAddressBatchParams) (int64, error)
	// diary_id 支持跨天编辑时把条目迁移到目标日期的日记（UpsertDiary 后由调用方传入）。
	UpdateDiaryEntry(ctx context.Context, arg UpdateDiaryEntryParams) (int64, error)
	// 参数按使用顺序连续编号，避免 $6 跳跃误导。
	UpdateMemory(ctx context.Context, arg UpdateMemoryParams) (Memory, error)
	UpdateOrderPaid(ctx context.Context, arg UpdateOrderPaidParams) (int64, error)
	UpdateUserAlertSubscribe(ctx context.Context, arg UpdateUserAlertSubscribeParams) error
	UpdateUserAutoRecord(ctx context.Context, arg UpdateUserAutoRecordParams) error
	UpdateUserAvatar(ctx context.Context, arg UpdateUserAvatarParams) error
	// 仅当 avatar 仍为空时写入：注册后异步默认头像回写不覆盖登录链路已写入的微信头像（02a A-9）。
	UpdateUserAvatarIfEmpty(ctx context.Context, arg UpdateUserAvatarIfEmptyParams) (int64, error)
	UpdateUserCurrentFamily(ctx context.Context, arg UpdateUserCurrentFamilyParams) error
	// 仅当尚无邀请人时写入（登录后补绑场景的幂等闸门）。
	UpdateUserInvitedBy(ctx context.Context, arg UpdateUserInvitedByParams) (int64, error)
	UpdateUserLang(ctx context.Context, arg UpdateUserLangParams) error
	UpdateUserLastActiveAt(ctx context.Context, id string) error
	UpdateUserNickname(ctx context.Context, arg UpdateUserNicknameParams) error
	UpdateUserPersonalFamily(ctx context.Context, arg UpdateUserPersonalFamilyParams) error
	UpdateUserSessionKey(ctx context.Context, arg UpdateUserSessionKeyParams) error
	UpdateUserUnionID(ctx context.Context, arg UpdateUserUnionIDParams) error
	UpdateUsersCurrentFamily(ctx context.Context, arg UpdateUsersCurrentFamilyParams) error
	UpdateWxMPAccountSubscribeStatus(ctx context.Context, arg UpdateWxMPAccountSubscribeStatusParams) error
	UpsertDiary(ctx context.Context, arg UpsertDiaryParams) (string, error)
	UpsertFamilyDailyCover(ctx context.Context, arg UpsertFamilyDailyCoverParams) error
	UpsertFamilyMembership(ctx context.Context, arg UpsertFamilyMembershipParams) (string, error)
	UpsertUserAvatarMarker(ctx context.Context, arg UpsertUserAvatarMarkerParams) error
	UpsertUserVIP(ctx context.Context, arg UpsertUserVIPParams) (UserVip, error)
	// open_id 冗余发放主体；不带目标的 ON CONFLICT DO NOTHING 同时覆盖
	// (user_id, vip_id) 与 (open_id, vip_id) 两级唯一，rowsAffected=0 → 409 已领取。
	UpsertVIPClaim(ctx context.Context, arg UpsertVIPClaimParams) (int64, error)
	UpsertWxMPAccount(ctx context.Context, arg UpsertWxMPAccountParams) (WxMpAccount, error)
}

var _ Querier = (*Queries)(nil)
