// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_common_address.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteUserCommonAddressByName = `-- name: DeleteUserCommonAddressByName :exec
DELETE FROM user_common_addresses
WHERE user_id = $1 AND name = $2
`

type DeleteUserCommonAddressByNameParams struct {
	UserID string `json:"userId"`
	Name   string `json:"name"`
}

func (q *Queries) DeleteUserCommonAddressByName(ctx context.Context, arg DeleteUserCommonAddressByNameParams) error {
	_, err := q.db.Exec(ctx, deleteUserCommonAddressByName, arg.UserID, arg.Name)
	return err
}

const deleteUserCommonAddresses = `-- name: DeleteUserCommonAddresses :exec
DELETE FROM user_common_addresses WHERE user_id = $1
`

func (q *Queries) DeleteUserCommonAddresses(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserCommonAddresses, userID)
	return err
}

const getLatestCoordinateByAddress = `-- name: GetLatestCoordinateByAddress :one
SELECT de.lat, de.lon
FROM diary_entries AS de
WHERE de.created_by = $1 AND de.address = $2
ORDER BY de.created_at DESC
LIMIT 1
`

type GetLatestCoordinateByAddressParams struct {
	CreatedBy string      `json:"createdBy"`
	Address   pgtype.Text `json:"address"`
}

type GetLatestCoordinateByAddressRow struct {
	Lat pgtype.Numeric `json:"lat"`
	Lon pgtype.Numeric `json:"lon"`
}

func (q *Queries) GetLatestCoordinateByAddress(ctx context.Context, arg GetLatestCoordinateByAddressParams) (GetLatestCoordinateByAddressRow, error) {
	row := q.db.QueryRow(ctx, getLatestCoordinateByAddress, arg.CreatedBy, arg.Address)
	var i GetLatestCoordinateByAddressRow
	err := row.Scan(&i.Lat, &i.Lon)
	return i, err
}

const getUserCommonAddress = `-- name: GetUserCommonAddress :one
SELECT name, lat, lon, count
FROM user_common_addresses
WHERE user_id = $1 AND name = $2
`

type GetUserCommonAddressParams struct {
	UserID string `json:"userId"`
	Name   string `json:"name"`
}

type GetUserCommonAddressRow struct {
	Name  string         `json:"name"`
	Lat   pgtype.Numeric `json:"lat"`
	Lon   pgtype.Numeric `json:"lon"`
	Count int32          `json:"count"`
}

func (q *Queries) GetUserCommonAddress(ctx context.Context, arg GetUserCommonAddressParams) (GetUserCommonAddressRow, error) {
	row := q.db.QueryRow(ctx, getUserCommonAddress, arg.UserID, arg.Name)
	var i GetUserCommonAddressRow
	err := row.Scan(
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.Count,
	)
	return i, err
}

const getUserCommonAddressForUpdate = `-- name: GetUserCommonAddressForUpdate :one
SELECT name, lat, lon, count
FROM user_common_addresses
WHERE user_id = $1 AND name = $2
FOR UPDATE
`

type GetUserCommonAddressForUpdateParams struct {
	UserID string `json:"userId"`
	Name   string `json:"name"`
}

type GetUserCommonAddressForUpdateRow struct {
	Name  string         `json:"name"`
	Lat   pgtype.Numeric `json:"lat"`
	Lon   pgtype.Numeric `json:"lon"`
	Count int32          `json:"count"`
}

func (q *Queries) GetUserCommonAddressForUpdate(ctx context.Context, arg GetUserCommonAddressForUpdateParams) (GetUserCommonAddressForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getUserCommonAddressForUpdate, arg.UserID, arg.Name)
	var i GetUserCommonAddressForUpdateRow
	err := row.Scan(
		&i.Name,
		&i.Lat,
		&i.Lon,
		&i.Count,
	)
	return i, err
}

const insertUserCommonAddresses = `-- name: InsertUserCommonAddresses :exec
INSERT INTO user_common_addresses (user_id, name, lat, lon, count, updated_at)
SELECT unnest($1::text[]),
       unnest($2::text[]),
       unnest($3::numeric[]),
       unnest($4::numeric[]),
       unnest($5::int[]),
       now()
`

type InsertUserCommonAddressesParams struct {
	UserIds []string         `json:"userIds"`
	Names   []string         `json:"names"`
	Lats    []pgtype.Numeric `json:"lats"`
	Lons    []pgtype.Numeric `json:"lons"`
	Counts  []int32          `json:"counts"`
}

func (q *Queries) InsertUserCommonAddresses(ctx context.Context, arg InsertUserCommonAddressesParams) error {
	_, err := q.db.Exec(ctx, insertUserCommonAddresses,
		arg.UserIds,
		arg.Names,
		arg.Lats,
		arg.Lons,
		arg.Counts,
	)
	return err
}

const listLatestCoordinatesByAddresses = `-- name: ListLatestCoordinatesByAddresses :many
SELECT DISTINCT ON (de.address)
    de.address AS name, de.lat, de.lon
FROM diary_entries AS de
WHERE de.created_by = $1 AND de.address = ANY($2::text[])
ORDER BY de.address, de.created_at DESC
`

type ListLatestCoordinatesByAddressesParams struct {
	CreatedBy string   `json:"createdBy"`
	Column2   []string `json:"column2"`
}

type ListLatestCoordinatesByAddressesRow struct {
	Name pgtype.Text    `json:"name"`
	Lat  pgtype.Numeric `json:"lat"`
	Lon  pgtype.Numeric `json:"lon"`
}

// 按地址批量取最新坐标（DISTINCT ON），避免循环内逐条 N+1 查询。
func (q *Queries) ListLatestCoordinatesByAddresses(ctx context.Context, arg ListLatestCoordinatesByAddressesParams) ([]ListLatestCoordinatesByAddressesRow, error) {
	rows, err := q.db.Query(ctx, listLatestCoordinatesByAddresses, arg.CreatedBy, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLatestCoordinatesByAddressesRow{}
	for rows.Next() {
		var i ListLatestCoordinatesByAddressesRow
		if err := rows.Scan(&i.Name, &i.Lat, &i.Lon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopAddressesByUser = `-- name: ListTopAddressesByUser :many
SELECT de.address AS name, COUNT(*) AS count
FROM diary_entries AS de
WHERE de.created_by = $1 AND de.address IS NOT NULL AND de.address <> ''
GROUP BY de.address
ORDER BY COUNT(*) DESC, MAX(de.created_at) DESC
LIMIT $2
`

type ListTopAddressesByUserParams struct {
	CreatedBy string `json:"createdBy"`
	Limit     int32  `json:"limit"`
}

type ListTopAddressesByUserRow struct {
	Name  pgtype.Text `json:"name"`
	Count int64       `json:"count"`
}

func (q *Queries) ListTopAddressesByUser(ctx context.Context, arg ListTopAddressesByUserParams) ([]ListTopAddressesByUserRow, error) {
	rows, err := q.db.Query(ctx, listTopAddressesByUser, arg.CreatedBy, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTopAddressesByUserRow{}
	for rows.Next() {
		var i ListTopAddressesByUserRow
		if err := rows.Scan(&i.Name, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserCommonAddresses = `-- name: ListUserCommonAddresses :many
SELECT name, lat, lon, count
FROM user_common_addresses
WHERE user_id = $1
ORDER BY count DESC, updated_at DESC
LIMIT 10
`

type ListUserCommonAddressesRow struct {
	Name  string         `json:"name"`
	Lat   pgtype.Numeric `json:"lat"`
	Lon   pgtype.Numeric `json:"lon"`
	Count int32          `json:"count"`
}

func (q *Queries) ListUserCommonAddresses(ctx context.Context, userID string) ([]ListUserCommonAddressesRow, error) {
	rows, err := q.db.Query(ctx, listUserCommonAddresses, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserCommonAddressesRow{}
	for rows.Next() {
		var i ListUserCommonAddressesRow
		if err := rows.Scan(
			&i.Name,
			&i.Lat,
			&i.Lon,
			&i.Count,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithDiaryChangesSince = `-- name: ListUsersWithDiaryChangesSince :many
SELECT DISTINCT de.created_by
FROM diary_entries AS de
WHERE de.updated_at >= $1 AND de.updated_at < $2
  AND de.created_by > $3
ORDER BY de.created_by
LIMIT $4
`

type ListUsersWithDiaryChangesSinceParams struct {
	UpdatedAt  pgtype.Timestamptz `json:"updatedAt"`
	UpdatedAt2 pgtype.Timestamptz `json:"updatedAt2"`
	Cursor     string             `json:"cursor"`
	Limit      int32              `json:"limit"`
}

// keyset 游标分页：按 created_by 排序 + 游标 + LIMIT，避免一次性物化全部变更用户。
func (q *Queries) ListUsersWithDiaryChangesSince(ctx context.Context, arg ListUsersWithDiaryChangesSinceParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listUsersWithDiaryChangesSince,
		arg.UpdatedAt,
		arg.UpdatedAt2,
		arg.Cursor,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var created_by string
		if err := rows.Scan(&created_by); err != nil {
			return nil, err
		}
		items = append(items, created_by)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeUserCommonAddress = `-- name: MergeUserCommonAddress :exec
INSERT INTO user_common_addresses (user_id, name, lat, lon, count, updated_at)
SELECT src.user_id, $3, src.lat, src.lon, src.count, now()
FROM user_common_addresses AS src
WHERE src.user_id = $1 AND src.name = $2
ON CONFLICT (user_id, name) DO UPDATE SET
    count = user_common_addresses.count + EXCLUDED.count,
    updated_at = now()
`

type MergeUserCommonAddressParams struct {
	UserID string `json:"userId"`
	Name   string `json:"name"`
	Name_2 string `json:"name2"`
}

// upsert 目标行（源行坐标/计数随 INSERT 带入），目标行不存在时计数不静默丢失；
// ON CONFLICT 保证并发合并计数不丢。源行删除由 DeleteUserCommonAddressByName 在调用方事务内完成
// （H2：sqlc 会静默丢弃同一 named 块中的第二条语句，不可合并写在这里）。
func (q *Queries) MergeUserCommonAddress(ctx context.Context, arg MergeUserCommonAddressParams) error {
	_, err := q.db.Exec(ctx, mergeUserCommonAddress, arg.UserID, arg.Name, arg.Name_2)
	return err
}

const needsCommonAddressRefresh = `-- name: NeedsCommonAddressRefresh :one
SELECT
  COALESCE(de_max.ts, '1970-01-01'::timestamptz) > COALESCE(ca_max.ts, '1970-01-01'::timestamptz)
  OR (ca_max.ts IS NOT NULL AND de_max.ts IS NULL) AS needs_refresh
FROM (SELECT MAX(updated_at) AS ts FROM user_common_addresses WHERE user_id = $1) ca_max
CROSS JOIN (SELECT MAX(updated_at) AS ts FROM diary_entries WHERE created_by = $1) de_max
`

func (q *Queries) NeedsCommonAddressRefresh(ctx context.Context, userID string) (pgtype.Bool, error) {
	row := q.db.QueryRow(ctx, needsCommonAddressRefresh, userID)
	var needs_refresh pgtype.Bool
	err := row.Scan(&needs_refresh)
	return needs_refresh, err
}

const renameUserCommonAddress = `-- name: RenameUserCommonAddress :exec
UPDATE user_common_addresses
SET name = $3, updated_at = now()
WHERE user_id = $1 AND name = $2
`

type RenameUserCommonAddressParams struct {
	UserID string `json:"userId"`
	Name   string `json:"name"`
	Name_2 string `json:"name2"`
}

func (q *Queries) RenameUserCommonAddress(ctx context.Context, arg RenameUserCommonAddressParams) error {
	_, err := q.db.Exec(ctx, renameUserCommonAddress, arg.UserID, arg.Name, arg.Name_2)
	return err
}

const updateDiaryEntriesAddress = `-- name: UpdateDiaryEntriesAddress :execrows
UPDATE diary_entries AS de
SET address = $3, updated_at = now()
WHERE de.created_by = $1 AND de.address = $2
`

type UpdateDiaryEntriesAddressParams struct {
	CreatedBy string      `json:"createdBy"`
	Address   pgtype.Text `json:"address"`
	Address_2 pgtype.Text `json:"address2"`
}

func (q *Queries) UpdateDiaryEntriesAddress(ctx context.Context, arg UpdateDiaryEntriesAddressParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDiaryEntriesAddress, arg.CreatedBy, arg.Address, arg.Address_2)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDiaryEntriesAddressBatch = `-- name: UpdateDiaryEntriesAddressBatch :execrows
UPDATE diary_entries AS de
SET address = $4, updated_at = now()
WHERE de.id IN (
    SELECT de_inner.id FROM diary_entries AS de_inner
    WHERE de_inner.created_by = $1 AND de_inner.address = $2
    ORDER BY de_inner.id ASC
    LIMIT $3
)
`

type UpdateDiaryEntriesAddressBatchParams struct {
	CreatedBy string      `json:"createdBy"`
	Address   pgtype.Text `json:"address"`
	Limit     int32       `json:"limit"`
	Address_2 pgtype.Text `json:"address2"`
}

func (q *Queries) UpdateDiaryEntriesAddressBatch(ctx context.Context, arg UpdateDiaryEntriesAddressBatchParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateDiaryEntriesAddressBatch,
		arg.CreatedBy,
		arg.Address,
		arg.Limit,
		arg.Address_2,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
